<?php

namespace App\Services\Erp;

use App\Exceptions\Erp\WorkOrderDomainException;
use App\Models\Erp\ProductionExecutionCommand;
use App\Models\Erp\ProductionQuantityOperation;
use App\Models\Erp\ProductionTask;
use App\Models\Erp\ProductionUnitOperation;
use Illuminate\Support\Facades\DB;

class ProductionInternalIssueService
{
    public function __construct(private readonly InventoryService $inventory) {}
    public function dispatch(int $id, array $payload, object $user, array $permissions): array
    { $this->permission($permissions, 'production.output.issue'); return $this->change('dispatch_internal_issue', $id, $payload, $user, function ($issue, $task, $target, $user): array { if ($issue->status !== 'WAIT_ISSUE') $this->fail('issue_not_waiting', '内部领用任务不处于待发料状态。', 409); if (! $task->assignee_user_legacy_id) $this->fail('target_task_not_claimed', '下一工序尚未接单，不能交付半成品。', 409); DB::table('erp_production_internal_issue_tasks')->where('id', $issue->id)->update(['status' => 'ISSUED', 'expected_receiver_legacy_id' => $task->assignee_user_legacy_id, 'issued_by_legacy_id' => $this->userId($user), 'issued_at' => now(), 'business_version' => (int) $issue->business_version + 1, 'updated_at' => now()]); return ['id' => (int) $issue->id, 'status' => 'ISSUED', 'business_version' => (int) $issue->business_version + 1]; }); }
    public function receive(int $id, array $payload, object $user, array $permissions): array
    { $this->permission($permissions, 'production.output.receive'); return $this->change('receive_internal_issue', $id, $payload, $user, function ($issue, $task, $target, $user): array { if ($issue->status !== 'ISSUED') $this->fail('issue_not_dispatched', '内部领用尚未由仓库交出。', 409); if ((int) $task->assignee_user_legacy_id !== $this->userId($user)) $this->fail('expected_receiver_required', '只有下一工序当前负责人可以确认接收。', 403); $lines = DB::table('erp_production_internal_issue_lines')->where('issue_task_id', $issue->id)->lockForUpdate()->get(); $transaction = $this->inventory->postProductionInternalIssue($issue, $lines, $user); foreach ($lines as $line) { if (! $line->target_material_requirement_id) continue; $requirement = DB::table('erp_production_target_material_requirements')->where('id', $line->target_material_requirement_id)->lockForUpdate()->first(); if (! $requirement || $requirement->target_type !== $issue->target_type || (int) $requirement->target_id !== (int) $issue->target_id) $this->fail('internal_issue_material_requirement_invalid', '内部领用绑定的目标物料需求无效，禁止接收。', 409); $satisfied = min((float) $requirement->required_base_qty, (float) $requirement->satisfied_base_qty + (float) $line->issue_base_qty); DB::table('erp_production_target_material_requirements')->where('id', $requirement->id)->update(['satisfied_base_qty' => $satisfied, 'status' => $satisfied + 0.00000001 >= (float) $requirement->required_base_qty ? 'SATISFIED' : 'PARTIAL', 'business_version' => (int) $requirement->business_version + 1, 'updated_at' => now()]); } DB::table('erp_production_internal_issue_tasks')->where('id', $issue->id)->update(['status' => 'RECEIVED', 'received_by_legacy_id' => $this->userId($user), 'received_at' => now(), 'inventory_transaction_id' => $transaction->id, 'business_version' => (int) $issue->business_version + 1, 'updated_at' => now()]); $target->status = $target->kitting_required && ! $target->kitting_confirmed_at ? 'WAIT_MATERIAL' : 'READY'; $target->business_version = (int) $target->business_version + 1; $target->save(); $task->targets()->where('target_type', $issue->target_type)->where('target_id', $issue->target_id)->update(['status_snapshot' => $target->status]); return ['id' => (int) $issue->id, 'status' => 'RECEIVED', 'inventory_transaction_id' => (int) $transaction->id, 'target_status' => $target->status, 'target_business_version' => (int) $target->business_version, 'business_version' => (int) $issue->business_version + 1]; }); }
    private function change(string $type, int $id, array $payload, object $user, callable $action): array
    { $commandId = trim((string) $payload['client_command_id']); $hash = hash('sha256', json_encode([$id, (int) $payload['expected_version']], JSON_UNESCAPED_UNICODE)); return DB::transaction(function () use ($type, $id, $payload, $user, $action, $commandId, $hash): array { $existing = ProductionExecutionCommand::where('client_command_id', $commandId)->lockForUpdate()->first(); if ($existing) { if ($existing->command_type !== $type || $existing->request_hash !== $hash) $this->fail('command_conflict', '该 client_command_id 已用于不同请求。', 409); return $existing->response_snapshot; } $ledger = ProductionExecutionCommand::create(['client_command_id' => $commandId, 'command_type' => $type, 'aggregate_type' => 'production_internal_issue', 'aggregate_id' => $id, 'request_hash' => $hash, 'status' => 'processing', 'initiated_by_legacy_id' => $this->userId($user), 'processing_started_at' => now()]); $issue = DB::table('erp_production_internal_issue_tasks')->where('id', $id)->lockForUpdate()->first(); if (! $issue) $this->fail('internal_issue_not_found', '生产内部领用任务不存在。', 404); if ((int) $issue->business_version !== (int) $payload['expected_version']) $this->fail('version_conflict', '内部领用任务版本已变化，请刷新后重试。', 409); $task = ProductionTask::query()->lockForUpdate()->findOrFail($issue->target_task_id); $target = $this->target($issue->target_type, (int) $issue->target_id); $result = $action($issue, $task, $target, $user); $ledger->update(['result_type' => 'production_internal_issue', 'result_id' => $id, 'response_snapshot' => $result, 'status' => 'succeeded', 'processing_finished_at' => now()]); return $result; }, 5); }
    private function target(string $type, int $id): object { $model = $type === 'unit_operation' ? ProductionUnitOperation::class : ProductionQuantityOperation::class; return $model::query()->lockForUpdate()->findOrFail($id); }
    private function permission(array $permissions, string $code): void { if (! in_array($code, $permissions, true)) $this->fail('permission_denied', '当前用户没有执行该操作的权限。', 403); }
    private function userId(object $user): int { return (int) ($user->legacy_id ?? $user->id ?? 0); }
    private function fail(string $code, string $message, int $status = 422): never { throw new WorkOrderDomainException($code, $message, $status); }
}
