<template>
  <section class="alert-workbench" v-loading="loading">
    <header class="heading">
      <div><h1>库存预警工作台</h1><p>按真实可用库存识别缺货、低库存和超储；同一状态只更新库存事实，不重复发送通知。</p></div>
      <div><el-button @click="openConfiguration">预警规则配置</el-button><el-button type="success" :disabled="!selected.length" @click="createRequest">生成采购需求</el-button></div>
    </header>
    <el-alert title="库存预警基于现有库存余额与可用库存服务；恢复正常后自动解除并保留完整状态历史。" type="info" :closable="false" show-icon />
    <section class="filter-card"><el-form inline size="small">
      <el-form-item label="预警状态"><el-select v-model="filters.alert_status" clearable placeholder="全部"><el-option label="低库存" value="low_stock"/><el-option label="缺货" value="out_of_stock"/><el-option label="超储" value="over_stock"/><el-option label="正常" value="normal"/></el-select></el-form-item>
      <el-form-item label="Item"><el-input v-model="filters.keyword" placeholder="编码 / 名称" clearable/></el-form-item>
      <el-form-item label="物料分类"><el-select v-model="filters.category_id" clearable filterable placeholder="全部"><el-option v-for="c in categories" :key="c.id" :label="c.category_name" :value="c.id"/></el-select></el-form-item>
      <el-form-item label="仓库"><el-select v-model="filters.warehouse_id" clearable filterable placeholder="全部"><el-option v-for="w in warehouses" :key="w.id" :label="w.warehouse_name" :value="w.id"/></el-select></el-form-item>
      <el-form-item label="处理状态"><el-select v-model="filters.is_active" clearable placeholder="全部"><el-option label="活跃预警" value="true"/><el-option label="已解除" value="false"/></el-select></el-form-item>
      <el-button type="success" size="small" @click="search">查询</el-button><el-button size="small" @click="reset">重置</el-button>
    </el-form></section>
    <section class="stats"><article><i class="el-icon-warning-outline orange"/><span>活跃预警<b>{{ stats.active }}</b></span></article><article><i class="el-icon-warning red"/><span>缺货<b>{{ stats.out }}</b></span></article><article><i class="el-icon-warning yellow"/><span>低库存<b>{{ stats.low }}</b></span></article><article><i class="el-icon-top green"/><span>超储<b>{{ stats.over }}</b></span></article></section>
    <section class="table-card"><el-table ref="table" :data="rows" border size="small" row-key="id" class="alert-table" @selection-change="selected=$event" @row-click="viewDetail">
      <el-table-column type="selection" width="46" @click.stop/><el-table-column label="Item编码" min-width="120"><template slot-scope="{row}"><el-button type="text" @click.stop="viewDetail(row)">{{ row.item && row.item.item_code }}</el-button></template></el-table-column><el-table-column label="Item名称" min-width="160"><template slot-scope="{row}">{{ row.item && row.item.item_name }}</template></el-table-column><el-table-column label="仓库" min-width="105"><template slot-scope="{row}">{{ row.warehouse && row.warehouse.warehouse_name }}</template></el-table-column><el-table-column prop="quantity_on_hand" label="账面库存" min-width="90"/><el-table-column prop="quantity_locked" label="已锁定/预留" min-width="100"/><el-table-column prop="quantity_defective" label="不良/待处理" min-width="100"/><el-table-column prop="available_qty" label="可用库存" min-width="90"/><el-table-column prop="min_stock_snapshot" label="最低库存" min-width="90"/><el-table-column prop="safety_stock_snapshot" label="安全库存" min-width="90"/><el-table-column prop="suggested_replenishment_qty_snapshot" label="建议补货" min-width="90"/><el-table-column label="当前状态" min-width="115"><template slot-scope="{row}"><el-tag size="mini" :type="tag(row.alert_status, row.severity)" @click.native.stop="viewDetail(row)">{{ label(row.alert_status, row.severity) }}</el-tag></template></el-table-column><el-table-column label="最近预警时间" min-width="145"><template slot-scope="{row}">{{ date(row.last_changed_at) }}</template></el-table-column><el-table-column label="操作" fixed="right" width="168"><template slot-scope="{row}"><el-button type="text" @click.stop="viewDetail(row)">查看详情</el-button><el-button v-if="!row.purchase_request_id && row.is_active" type="text" @click.stop="createRequestFor(row)">生成需求</el-button><el-button v-else-if="row.purchase_request_id" type="text" @click.stop="openPurchaseRequest(row)">查看需求</el-button></template></el-table-column>
    </el-table><div class="pager"><span>共 {{ total }} 条</span><el-pagination background layout="prev, pager, next, sizes, jumper" :current-page="page" :page-size="perPage" :page-sizes="[10,20,50]" :total="total" @current-change="changePage" @size-change="changeSize"/></div></section>
    <p class="foot-note"><i class="el-icon-info"/> 采购需求只带出 Item、建议补货数量、目标仓库与预警来源；不会直接生成采购订单。</p>
  </section>
</template>
<script>
import { listInventoryAlerts, createPurchaseRequestFromInventoryAlert } from '@/api/erp/inventory'
import { listEntity, listItemCategories } from '@/api/erp/master'
export default { name:'InventoryAlertWorkbench', data:()=>({loading:false,rows:[],warehouses:[],categories:[],selected:[],page:1,perPage:10,total:0,serverStats:{active:0,out:0,low:0,over:0},filters:{alert_status:'',keyword:'',category_id:'',warehouse_id:'',is_active:'true'}}), computed:{stats(){return this.serverStats}}, created(){this.load();listEntity('warehouses',{per_page:100}).then(r=>{this.warehouses=r.data.data||[]});listItemCategories({per_page:100}).then(r=>{this.categories=r.data.data||[]})}, methods:{async load(){this.loading=true;try{const r=await listInventoryAlerts({...this.filters,page:this.page,per_page:this.perPage});this.rows=r.data.data||[];this.total=r.data.total||0;this.serverStats=r.data.stats||{active:0,out:0,low:0,over:0};this.selected=[]}catch(e){this.$message.error(e.userMessage||'库存预警加载失败')}finally{this.loading=false}},search(){this.page=1;this.load()},reset(){this.filters={alert_status:'',keyword:'',category_id:'',warehouse_id:'',is_active:'true'};this.search()},changePage(page){this.page=page;this.load()},changeSize(size){this.perPage=size;this.page=1;this.load()},tag(status,severity){if(status==='out_of_stock'||severity==='critical')return 'danger';if(status==='low_stock')return 'warning';if(status==='over_stock')return 'info';return 'success'},label(status,severity){if(status==='low_stock')return severity==='critical'?'低库存（严重）':'低库存（一般）';return ({out_of_stock:'缺货（严重）',over_stock:'超储',normal:'正常'})[status]||status},viewDetail(row){if(row&&row.id)this.$router.push(`/inventory/alerts/${row.id}`)},openConfiguration(){if(this.selected.length!==1)return this.$message.info('请先在预警列表勾选一条 Item，再配置对应的库存预警规则。');this.$router.push(`/inventory/alerts/config?item_id=${this.selected[0].item_id}`)},async createRequestFor(row){try{const result=await createPurchaseRequestFromInventoryAlert(row.id);const request=result.data.data;this.$message.success('已生成采购需求草稿');this.$router.push(`/purchase/requests/${request.id}/edit`)}catch(e){this.$message.error(e.userMessage||'生成采购需求失败')}},async createRequest(){if(!this.selected.length)return;try{const result=await Promise.all(this.selected.map(row=>createPurchaseRequestFromInventoryAlert(row.id)));const request=result[0].data.data;this.$message.success(`已生成 ${result.length} 条采购需求草稿`);this.$router.push(`/purchase/requests/${request.id}/edit`)}catch(e){this.$message.error(e.userMessage||'生成采购需求失败')}},openPurchaseRequest(row){this.$router.push(`/purchase/requests/${row.purchase_request_id}/edit`)},date(value){return value?String(value).replace('T',' ').replace('.000000Z',''): '-'}}}
</script>
<style scoped>
.alert-workbench{min-height:calc(100vh - 52px);padding:22px 24px 32px;background:#f7f9fb;color:#172033;box-sizing:border-box}.heading{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:15px;gap:20px}.heading h1{font-size:28px;margin:0 0 7px}.heading p{margin:0;color:#6f7b8b;font-size:14px}.heading .el-button{height:40px;margin-left:10px}.heading .el-button--success{background:#07883f;border-color:#07883f}.el-alert{border:1px solid #b8d7ff;background:#f4f9ff;margin-bottom:15px}.filter-card,.table-card{background:#fff;border:1px solid #e2e8f0;border-radius:7px;padding:16px;margin-bottom:14px}.filter-card .el-form-item{margin-bottom:0;margin-right:22px}.filter-card .el-input,.filter-card .el-select{width:178px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:14px}.stats article{height:88px;display:flex;align-items:center;gap:14px;padding:0 20px;border:1px solid #e2e8f0;border-radius:7px;background:#fff}.stats i{width:42px;height:42px;border-radius:8px;text-align:center;line-height:42px;font-size:25px}.stats span{color:#687588;font-size:13px}.stats b{display:block;font-size:27px;line-height:30px;color:#172033}.orange{color:#ed8b1d;background:#fff4df}.red{color:#e24242;background:#fff0f0}.yellow{color:#ef9d12;background:#fff8e6}.green{color:#07883f;background:#e9f8ef}.table-card{padding:0;overflow:hidden}.alert-table{cursor:pointer}.table-card :deep(.el-table th){height:45px;background:#f6f8fb;color:#465266}.table-card :deep(.el-table td){height:48px}.pager{display:flex;align-items:center;justify-content:space-between;padding:13px 18px}.foot-note{margin:0;padding:13px 15px;border:1px solid #b8d7ff;border-radius:5px;background:#f4f9ff;color:#3471c8;font-size:13px}.foot-note i{font-size:17px;margin-right:6px}@media(max-width:1450px){.table-card{overflow-x:auto}.table-card .el-table{min-width:1450px}.pager{min-width:980px}}@media(max-width:1100px){.stats{grid-template-columns:repeat(2,1fr)}.filter-card .el-form-item{margin-bottom:10px}}@media(max-width:720px){.alert-workbench{padding:16px 12px}.heading{display:block}.heading>div:last-child{margin-top:12px}.heading .el-button{margin-left:0;margin-right:8px}.stats{grid-template-columns:1fr}.filter-card .el-form{display:flex;flex-direction:column}.filter-card .el-form-item{margin-right:0}.filter-card .el-input,.filter-card .el-select{width:100%}}
</style>
