import api from './master'

export const listFinanceAccounts = params => api.get('/v1/erp/finance/accounts', { params })
export const createFinanceAccount = data => api.post('/v1/erp/finance/accounts', data)
export const updateFinanceAccount = (id, data) => api.put(`/v1/erp/finance/accounts/${id}`, data)
export const setFinanceAccountStatus = (id, status) => api.post(`/v1/erp/finance/accounts/${id}/status`, { status })
export const listFinanceCurrencies = params => api.get('/v1/erp/finance/currencies', { params })
export const listExchangeRateHistory = params => api.get('/v1/erp/finance/exchange-rate-history', { params })
export const createExchangeRate = data => api.post('/v1/erp/finance/exchange-rates', data)
export const disableExchangeRate = id => api.post(`/v1/erp/finance/exchange-rates/${id}/disable`)
export const listFinanceAccountValuations = params => api.get('/v1/erp/finance/accounts/valuations', { params })
export const listFinanceTransfers = params => api.get('/v1/erp/finance/transfers', { params })
export const getFinanceTransfer = id => api.get(`/v1/erp/finance/transfers/${id}`)
export const previewFinanceTransfer = data => api.post('/v1/erp/finance/transfers/preview', data)
export const createFinanceTransfer = data => api.post('/v1/erp/finance/transfers', data)
export const updateFinanceTransfer = (id, data) => api.put(`/v1/erp/finance/transfers/${id}`, data)
export const confirmFinanceTransfer = (id, previewToken) => api.post(`/v1/erp/finance/transfers/${id}/confirm`, { preview_token: previewToken })
export const voidFinanceTransfer = (id, reason) => api.post(`/v1/erp/finance/transfers/${id}/void`, { reason })
export const uploadTransferAttachment = (id, form) => api.post(`/v1/erp/finance/transfers/${id}/attachments`, form, { headers: { 'Content-Type': 'multipart/form-data' } })

export const listCashDocuments = (direction, params) => api.get(`/v1/erp/finance/cash-documents/${direction}`, { params })
export const getCashDocument = id => api.get(`/v1/erp/finance/cash-documents/show/${id}`)
export const createCashDocument = (direction, data) => api.post(`/v1/erp/finance/cash-documents/${direction}`, data)
export const updateCashDocument = (id, data) => api.put(`/v1/erp/finance/cash-documents/${id}`, data)
export const confirmCashDocument = id => api.post(`/v1/erp/finance/cash-documents/${id}/confirm`)
export const voidCashDocument = (id, reason) => api.post(`/v1/erp/finance/cash-documents/${id}/void`, { reason })
export const allocateCashDocument = (id, items) => api.post(`/v1/erp/finance/cash-documents/${id}/allocations`, { items })
export const reverseFinanceAllocation = (id, reason) => api.post(`/v1/erp/finance/allocations/${id}/reverse`, { reason })
export const resolveFinanceSource = params => api.get('/v1/erp/finance/sources/resolve', { params })
export const listFinanceSources = params => api.get('/v1/erp/finance/sources', { params })
export const listFinancePayables = params => api.get('/v1/erp/finance/payables', { params })
export const listFinanceSupplierLedgers = params => api.get('/v1/erp/finance/supplier-ledgers', { params })
export const listFinanceInvoices = params => api.get('/v1/erp/finance/invoices', { params })
export const getFinanceInvoice = id => api.get(`/v1/erp/finance/invoices/${id}`)
export const getFinanceInvoiceDetail = (id, params) => api.get(`/v1/erp/finance/invoices/${id}/detail`, { params })
export const getFinanceInvoiceRedPreview = id => api.get(`/v1/erp/finance/invoices/${id}/red-preview`)
export const createFinanceRedInvoice = (id, data) => api.post(`/v1/erp/finance/invoices/${id}/red`, data)
export const createFinanceRedInvoiceDraft = (id, data) => api.post(`/v1/erp/finance/invoices/${id}/red-draft`, data)
export const confirmFinanceRedInvoiceDraft = id => api.post(`/v1/erp/finance/invoices/red-drafts/${id}/confirm`)
export const createFinanceInvoice = data => api.post('/v1/erp/finance/invoices', data)
export const updateFinanceInvoice = (id, data) => api.put(`/v1/erp/finance/invoices/${id}`, data)
export const listInvoiceMatchingSources = (id, params) => api.get(`/v1/erp/finance/invoices/${id}/matching-sources`, { params })
export const saveFinanceInvoiceMatches = (id, items) => api.put(`/v1/erp/finance/invoices/${id}/matches`, { items })
export const confirmFinanceInvoice = id => api.post(`/v1/erp/finance/invoices/${id}/confirm`)
export const reverseFinanceInvoiceMatch = (id, reason) => api.post(`/v1/erp/finance/invoices/allocations/${id}/reverse`, { reason })
export const uploadFinanceInvoiceAttachment = (id, form) => api.post(`/v1/erp/finance/invoices/${id}/attachments`, form, { headers: { 'Content-Type': 'multipart/form-data' } })
export const deleteFinanceInvoiceAttachment = id => api.delete(`/v1/erp/finance/invoices/attachments/${id}`)
export const getCounterpartyBalance = (partyType, partyId) => api.get(`/v1/erp/finance/counterparties/${partyType}/${partyId}/balance`)

export const uploadFinanceAttachment = (id, form) => api.post(`/v1/erp/finance/cash-documents/${id}/attachments`, form, { headers: { 'Content-Type': 'multipart/form-data' } })
export const previewFinanceAttachment = id => api.get(`/v1/erp/finance/attachments/${id}/preview`, { responseType: 'blob' })
export const deleteFinanceAttachment = id => api.delete(`/v1/erp/finance/attachments/${id}`)
