import api from './master'

export const listPendingReceipts = params => api.get('/v1/erp/inventory/posting/pending-receipts', { params })
export const getPostingReceipt = id => api.get(`/v1/erp/inventory/posting/receipts/${id}`)
export const repairPostingReceiptAllocations = (id, data) => api.put(`/v1/erp/inventory/posting/receipts/${id}/allocations`, data)
export const postPostingReceipt = (id, payload = {}) => api.post(`/v1/erp/inventory/posting/receipts/${id}/post`, payload)

export const listInventoryBalances = params => api.get('/v1/erp/inventory/balances', { params })
export const getInventoryBalance = id => api.get(`/v1/erp/inventory/balances/${id}`)
export const listInventoryItemBatches = (itemId, params) => api.get(`/v1/erp/inventory/balances/items/${itemId}/batches`, { params })
export const getInventoryBatchContext = (itemId, params) => api.get(`/v1/erp/inventory/balances/items/${itemId}/batch-context`, { params })
export const listInventoryBalanceSerials = (balanceId, params) => api.get(`/v1/erp/inventory/balances/${balanceId}/serials`, { params })

export const getInventoryQualityContext = balanceId => api.get(`/v1/erp/inventory/quality-events/context/${balanceId}`)
export const listInventoryQualityEvents = params => api.get('/v1/erp/inventory/quality-events', { params })
export const createInventoryQualityEvent = data => api.post('/v1/erp/inventory/quality-events', data)
export const getInventoryQualityEvent = id => api.get(`/v1/erp/inventory/quality-events/${id}`)
export const startInventoryQualityEvent = id => api.post(`/v1/erp/inventory/quality-events/${id}/start`)
export const completeInventoryQualityEvent = (id, data) => api.post(`/v1/erp/inventory/quality-events/${id}/complete`, data)

export const listInventoryTransactions = params => api.get('/v1/erp/inventory/transactions', { params })
export const getInventoryTransaction = id => api.get(`/v1/erp/inventory/transactions/${id}`)

export const listInventoryAdjustments = params => api.get('/v1/erp/inventory/adjustments', { params })
export const listInventoryAdjustmentReasons = () => api.get('/v1/erp/inventory/adjustments/reasons')
export const generateInventoryAdjustmentSerials = data => api.post('/v1/erp/inventory/adjustments/serials/generate', data)
export const saveInventoryAdjustment = data => data.id ? api.put(`/v1/erp/inventory/adjustments/${data.id}`, data) : api.post('/v1/erp/inventory/adjustments', data)
export const submitInventoryAdjustment = id => api.post(`/v1/erp/inventory/adjustments/${id}/submit`)
export const postInventoryAdjustment = id => api.post(`/v1/erp/inventory/adjustments/${id}/post`)
export const cancelInventoryAdjustment = id => api.post(`/v1/erp/inventory/adjustments/${id}/cancel`)
export const deleteInventoryAdjustment = id => api.delete(`/v1/erp/inventory/adjustments/${id}`)
export const listInventoryAlerts = params => api.get('/v1/erp/inventory/alerts', { params })
export const getInventoryAlert = (id, params = {}) => api.get(`/v1/erp/inventory/alerts/${id}`, { params })
export const getInventoryAlertPolicy = itemId => api.get(`/v1/erp/inventory/alerts/policies/${itemId}`)
export const saveInventoryAlertPolicy = (itemId, data) => api.put(`/v1/erp/inventory/alerts/policies/${itemId}`, data)
export const activateInventoryAlertPolicy = (itemId, data) => api.post(`/v1/erp/inventory/alerts/policies/${itemId}/activate`, data)
export const disableInventoryAlertPolicy = (itemId, data = {}) => api.post(`/v1/erp/inventory/alerts/policies/${itemId}/disable`, data)
export const markInventoryAlertRead = id => api.post(`/v1/erp/inventory/alerts/${id}/read`)
export const listUnreadInventoryAlerts = params => api.get('/v1/erp/inventory/alerts/unread', { params })
export const createPurchaseRequestFromInventoryAlert = id => api.post(`/v1/erp/inventory/alerts/${id}/purchase-request`)
