import api from './master'

export const listPurchase = (type, params) => api.get(`/v1/erp/purchase/${type}`, { params })
export const getPurchase = (type, id) => api.get(`/v1/erp/purchase/${type}/${id}`)
export const savePurchaseRequest = data => data.id ? api.put(`/v1/erp/purchase/requests/${data.id}`, data) : api.post('/v1/erp/purchase/requests', data)
export const savePurchasePlan = data => data.id ? api.put(`/v1/erp/purchase/plans/${data.id}`, data) : api.post('/v1/erp/purchase/plans', data)
export const savePurchaseOrder = data => data.id ? api.put(`/v1/erp/purchase/orders/${data.id}`, data) : api.post('/v1/erp/purchase/orders', data)
export const savePurchaseReceipt = data => data.id ? api.put(`/v1/erp/purchase/receipts/${data.id}`, data) : api.post('/v1/erp/purchase/receipts', data)
export const deletePurchaseDraft = (type, id) => api.delete(`/v1/erp/purchase/${type}/${id}`)
export const generateReceiptSerials = data => api.post('/v1/erp/purchase/receipts/serials/generate', data)
export const uploadPurchaseAttachment = form => api.post('/v1/erp/purchase/attachments/upload', form, { headers: { 'Content-Type': 'multipart/form-data' } })
export const previewPurchaseAttachment = id => api.get(`/v1/erp/purchase/attachments/${id}/preview`, { responseType: 'blob' })
export const downloadPurchaseAttachment = id => api.get(`/v1/erp/purchase/attachments/${id}/download`, { responseType: 'blob' })
export const deletePurchaseAttachment = id => api.delete(`/v1/erp/purchase/attachments/${id}`)

export const submitRequest = id => api.post(`/v1/erp/purchase/requests/${id}/submit`)
export const closeRequest = id => api.post(`/v1/erp/purchase/requests/${id}/close`)
export const cancelRequest = id => api.post(`/v1/erp/purchase/requests/${id}/cancel`)
export const requestToPlan = id => api.post(`/v1/erp/purchase/requests/${id}/to-plan`)

export const submitPlan = id => api.post(`/v1/erp/purchase/plans/${id}/submit`)
export const approvePlan = id => api.post(`/v1/erp/purchase/plans/${id}/approve`)
export const rejectPlan = (id, data) => api.post(`/v1/erp/purchase/plans/${id}/reject`, data)
export const previewPlanOrders = id => api.get(`/v1/erp/purchase/plans/${id}/orders-preview`)
export const generatePlanOrders = id => api.post(`/v1/erp/purchase/plans/${id}/generate-orders`)

export const submitOrder = id => api.post(`/v1/erp/purchase/orders/${id}/submit`)
export const approveOrder = id => api.post(`/v1/erp/purchase/orders/${id}/approve`)
export const rejectOrder = id => api.post(`/v1/erp/purchase/orders/${id}/reject`)
export const cancelOrder = id => api.post(`/v1/erp/purchase/orders/${id}/cancel`)
export const closeOrder = id => api.post(`/v1/erp/purchase/orders/${id}/close`)
export const orderToReceipt = id => api.post(`/v1/erp/purchase/orders/${id}/to-receipt`)

export const confirmReceipt = id => api.post(`/v1/erp/purchase/receipts/${id}/confirm`)
export const listDefectHandlings = params => api.get('/v1/erp/purchase/defect-handlings', { params })
export const saveDefectHandling = data => api.post('/v1/erp/purchase/defect-handlings', data)
export const actionDefectHandling = (id, data) => api.post(`/v1/erp/purchase/defect-handlings/${id}/actions`, data)
export const listPurchaseExchangeOrders = params => api.get('/v1/erp/purchase/exchange-orders', { params })
export const getPurchaseExchangeOrder = id => api.get(`/v1/erp/purchase/exchange-orders/${id}`)
export const actionPurchaseExchangeOrder = (id, data) => api.post(`/v1/erp/purchase/exchange-orders/${id}/actions`, data)
export const listPriceHistories = params => api.get('/v1/erp/purchase/price-histories', { params })
export const listSupplierItemStats = params => api.get('/v1/erp/purchase/supplier-item-stats', { params })
export const getSupplierRecommendations = (itemId, params) => api.get(`/v1/erp/purchase/items/${itemId}/supplier-recommendations`, { params })

export const listPurchaseReturns = params => api.get('/v1/erp/purchase/returns', { params })
export const listPurchaseReturnSources = params => api.get('/v1/erp/purchase/returns/sources', { params })
export const listPurchaseReturnSourceSerials = (transactionItemId, params) => api.get(`/v1/erp/purchase/returns/sources/${transactionItemId}/serials`, { params })
export const getPurchaseReturn = id => api.get(`/v1/erp/purchase/returns/${id}`)
export const createPurchaseReturn = data => api.post('/v1/erp/purchase/returns', data)
export const submitPurchaseReturn = id => api.post(`/v1/erp/purchase/returns/${id}/submit`)
export const approvePurchaseReturn = id => api.post(`/v1/erp/purchase/returns/${id}/approve`)
export const postPurchaseReturn = id => api.post(`/v1/erp/purchase/returns/${id}/post`)
export const cancelPurchaseReturn = id => api.post(`/v1/erp/purchase/returns/${id}/cancel`)
export const closePurchaseReturn = id => api.post(`/v1/erp/purchase/returns/${id}/close`)
