import api from './master'

export const listPermissions = params => api.get('/v1/erp/rbac/permissions', { params })
export const savePermission = data => api.post('/v1/erp/rbac/permissions', data)
export const listRoles = params => api.get('/v1/erp/rbac/roles', { params })
export const saveRole = data => api.post('/v1/erp/rbac/roles', data)
export const deleteRole = (id, data = {}) => api.delete(`/v1/erp/rbac/roles/${id}`, { data })
export const listRoleUsers = (roleId, params = {}) => api.get('/v1/erp/rbac/role-users', { params: { role_id: roleId, ...params } })
export const saveRoleUsers = data => api.post('/v1/erp/rbac/role-users', data)
export const listDepartments = params => api.get('/v1/erp/departments', { params })
export const listDepartmentMembers = (id, params = {}) => api.get(`/v1/erp/departments/${id}/members`, { params })
export const saveDepartmentPrincipals = (id, principalIds, data = {}) => api.post(`/v1/erp/departments/${id}/principals`, { principal_ids: principalIds, ...data })
export const saveDepartment = data => data.legacy_id
  ? api.put(`/v1/erp/departments/${data.legacy_id}`, data)
  : api.post('/v1/erp/departments', data)
export const deleteDepartment = (id, data) => api.delete(`/v1/erp/departments/${id}`, { data })
export const listUsers = params => api.get('/v1/erp/user-directory/users', { params })
export const getAdmin = id => api.get(`/v1/erp/admins/${id}`)
export const saveAdmin = data => data.id ? api.put(`/v1/erp/admins/${data.id}`, data) : api.post('/v1/erp/admins', data)
export const setAdminStatus = (id, data) => api.post(`/v1/erp/admins/${id}/status`, data)
export const deleteAdmin = (id, data) => api.delete(`/v1/erp/admins/${id}`, { data })
export const getSystemOptions = () => api.get('/v1/erp/admins/options')
export const listRoleOptions = params => api.get('/v1/erp/admins/options/roles', { params })
export const listSystemUserOptions = params => api.get('/v1/erp/admins/options/users', { params })
export const syncDepartments = () => api.post('/v1/erp/departments/sync')
