<template>
  <section class="production-page" v-loading="loading"><div class="page-heading"><div><p class="eyebrow">生产管理 / 生产基础 / 工序管理</p><h1>{{ title }}</h1><p>工序编码由系统按编号规则预生成并保证唯一</p></div><el-button @click="$router.push('/production/operations')">返回列表</el-button></div>
    <section class="form-card"><el-form ref="form" :model="form" :rules="rules" label-position="top"><div class="form-grid"><el-form-item label="工序编码"><el-input v-model="form.operation_no" disabled/></el-form-item><el-form-item label="工序名称" prop="operation_name"><el-input v-model="form.operation_name" :disabled="viewOnly" maxlength="160"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sort" :disabled="viewOnly" :min="0" :max="999999"/></el-form-item><el-form-item label="状态"><el-input :value="form.status==='disabled'?'已停用':'已启用'" disabled/></el-form-item></div><el-form-item label="说明"><el-input v-model="form.description" :disabled="viewOnly" type="textarea" :rows="5" maxlength="2000" show-word-limit/></el-form-item><div v-if="!viewOnly" class="form-actions"><el-button @click="$router.push('/production/operations')">取消</el-button><el-button type="success" @click="save">保存</el-button></div></el-form></section>
  </section>
</template>
<script>
import { reserveProductionNumber,getProductionOperation,createProductionOperation,updateProductionOperation } from '../../../api/erp/production'
const uuid=()=>window.crypto&&window.crypto.randomUUID?window.crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})
export default {name:'ProductionOperationForm',data:()=>({loading:false,sessionId:'',reservationToken:'',form:{operation_no:'正在生成…',operation_name:'',sort:0,status:'enabled',description:'',business_version:1},rules:{operation_name:[{required:true,message:'请输入工序名称',trigger:'blur'}]}}),computed:{id(){return this.$route.params.id},viewOnly(){return !!this.id&&!this.$route.path.endsWith('/edit')},title(){return this.id?(this.viewOnly?'查看工序':'编辑工序'):'新增工序'}},created(){this.id?this.load():this.reserve()},methods:{async reserve(){this.loading=true;this.sessionId=uuid();try{const r=await reserveProductionNumber('operation',this.sessionId,this.$route.path);this.form.operation_no=r.data.data.document_no;this.reservationToken=r.data.data.reservation_token}catch(e){this.$message.error(e.userMessage||'编号生成失败')}finally{this.loading=false}},async load(){this.loading=true;try{const r=await getProductionOperation(this.id);this.form={...this.form,...r.data.data}}catch(e){this.$message.error(e.userMessage||'工序加载失败')}finally{this.loading=false}},save(){this.$refs.form.validate(async ok=>{if(!ok)return;this.loading=true;try{if(this.id){await updateProductionOperation(this.id,{client_command_id:`operation-update-${this.id}-${Date.now()}`,expected_version:this.form.business_version,operation_name:this.form.operation_name,sort:this.form.sort,description:this.form.description})}else{await createProductionOperation({client_command_id:`operation-create-${this.sessionId}`,creation_session_id:this.sessionId,reservation_token:this.reservationToken,operation_name:this.form.operation_name,sort:this.form.sort,status:'enabled',description:this.form.description})}this.$message.success('工序已保存');this.$router.push('/production/operations')}catch(e){this.$message.error(e.userMessage||'保存失败')}finally{this.loading=false}})}}}
</script>
<style scoped src="./production-master.css"></style>
