<template>
  <section class="production-page" v-loading="loading">
    <div class="page-heading"><div><p class="eyebrow">生产管理 / 生产基础</p><h1>工序管理</h1><p>维护生产路线所引用的正式工序主数据</p></div><el-button v-if="$can('production.operation.create')" type="success" @click="$router.push('/production/operations/new')">新增工序</el-button></div>
    <section class="filter-card"><div class="filter-grid"><label><span>工序编码 / 名称</span><el-input v-model="filters.keyword" clearable placeholder="请输入工序编码或名称" @keyup.enter.native="search" /></label><label><span>状态</span><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option label="已启用" value="enabled"/><el-option label="已停用" value="disabled"/></el-select></label></div><div class="filter-actions"><el-button @click="reset">重置</el-button><el-button type="success" @click="search">查询</el-button></div></section>
    <p class="result-count">共 {{ total }} 条</p>
    <section class="table-card"><el-table :data="rows" border><el-table-column prop="operation_no" label="工序编码" min-width="150"/><el-table-column prop="operation_name" label="工序名称" min-width="180"/><el-table-column prop="sort" label="排序" width="90"/><el-table-column label="状态" width="100"><template slot-scope="s"><el-tag size="mini" :type="s.row.status==='enabled'?'success':'info'">{{ s.row.status==='enabled'?'已启用':'已停用' }}</el-tag></template></el-table-column><el-table-column prop="description" label="说明" min-width="240" show-overflow-tooltip/><el-table-column label="操作" width="230"><template slot-scope="s"><el-button type="text" @click="$router.push(`/production/operations/${s.row.id}`)">查看</el-button><el-button v-if="$can('production.operation.edit')" type="text" @click="$router.push(`/production/operations/${s.row.id}/edit`)">编辑</el-button><el-button v-if="$can('production.operation.toggle')" type="text" @click="toggle(s.row)">{{ s.row.status==='enabled'?'停用':'启用' }}</el-button></template></el-table-column></el-table><div class="table-footer"><span>共 {{ total }} 条</span><el-pagination background layout="prev, pager, next" :current-page="page" :page-size="20" :total="total" @current-change="changePage"/></div></section>
  </section>
</template>
<script>
import { listProductionOperations, enableProductionOperation, disableProductionOperation } from '../../../api/erp/production'
export default { name:'ProductionOperationList', data:()=>({loading:false,rows:[],total:0,page:1,filters:{keyword:'',status:''}}), created(){this.load()}, methods:{ async load(){this.loading=true;try{const r=await listProductionOperations({...this.filters,page:this.page,per_page:20});this.rows=r.data.data||[];this.total=r.data.total||0}catch(e){this.$message.error(e.userMessage||'工序加载失败')}finally{this.loading=false}},search(){this.page=1;this.load()},reset(){this.filters={keyword:'',status:''};this.search()},changePage(v){this.page=v;this.load()},async toggle(row){try{await this.$confirm(`确认${row.status==='enabled'?'停用':'启用'}工序“${row.operation_name}”？`,'状态确认',{type:'warning'});const fn=row.status==='enabled'?disableProductionOperation:enableProductionOperation;await fn(row.id,{client_command_id:`operation-toggle-${row.id}-${Date.now()}`,expected_version:row.business_version});this.$message.success('工序状态已更新');this.load()}catch(e){if(e!=='cancel'&&e!=='close')this.$message.error(e.userMessage||'操作失败')}}}}
</script>
<style scoped src="./production-master.css"></style>
