<template>
  <div class="monitor-page">
    <div class="page-heading"><div><p class="eyebrow">生产管理 / 生产执行监管</p><h1>生产执行监管</h1></div></div>
    <div class="stats"><div v-for="s in statCards" :key="s.key"><span>{{s.label}}</span><strong>{{stats[s.key]||0}}</strong><small>{{s.unit}}</small></div></div>
    <section class="filter-card"><el-date-picker v-model="filters.planned_date" value-format="yyyy-MM-dd" placeholder="计划日期"/><el-input v-model="filters.keyword" placeholder="工单号 / 产品编号 / 名称" clearable/><el-select v-model="filters.status" placeholder="全部状态" clearable><el-option label="已发布" value="RELEASED"/><el-option label="执行中" value="IN_PROGRESS"/><el-option label="已完成" value="COMPLETED"/></el-select><el-button @click="reset">重置</el-button><el-button type="success" @click="load">查询</el-button></section>
    <section class="table-card"><h3>工单 / 任务汇总</h3><el-table :data="rows" border v-loading="loading" @row-click="openOrder"><el-table-column prop="work_order_no" label="工单编号" min-width="155"/><el-table-column label="产品编号 / 名称" min-width="210"><template slot-scope="s"><span>{{s.row.output_item&&s.row.output_item.item_code}}</span><small>{{s.row.output_item&&s.row.output_item.item_name}}</small></template></el-table-column><el-table-column prop="target_base_qty" label="计划数量" width="95"/><el-table-column label="执行模式" width="95"><template slot-scope="s">{{s.row.production_execution_mode_snapshot==='unit'?'逐件':'数量'}}</template></el-table-column><el-table-column prop="production_units_count" label="生产单元" width="95"/><el-table-column prop="production_tasks_count" label="任务" width="75"/><el-table-column label="状态" width="90"><template slot-scope="s"><el-tag size="mini">{{status(s.row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="75"><template slot-scope="s"><el-button type="text" @click.stop="openOrder(s.row)">查看</el-button></template></el-table-column></el-table><div class="table-footer"><span>共 {{total}} 条</span><el-pagination background layout="prev,pager,next" :page-size="10" :total="total" :current-page="page" @current-change="p=>{page=p;load()}"/></div></section>
    <section v-if="selected" class="table-card unit-card"><h3>生产单元明细（工单：{{selected.work_order_no}}）</h3><el-table :data="units" border><el-table-column prop="unit_no" label="生产单元号" min-width="150"/><el-table-column prop="device_no" label="设备编号" min-width="140"/><el-table-column prop="current_operation_name" label="当前工序" min-width="130"/><el-table-column label="状态" width="100"><template slot-scope="s">{{status(s.row.status)}}</template></el-table-column><el-table-column label="操作" width="75"><template slot-scope="s"><el-button type="text" @click="openUnit(s.row)">详情</el-button></template></el-table-column></el-table></section>
    <el-drawer title="生产单元详情" :visible.sync="drawer" size="390px"><div v-if="unit" class="drawer-body"><h2>{{unit.unit_no}}</h2><p>设备编号：{{unit.device_no||'-'}}</p><el-tabs v-model="tab"><el-tab-pane label="物料配送" name="material"><el-table :data="unit.operations" size="mini"><el-table-column prop="operation_name" label="工序"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane><el-tab-pane label="工时" name="labor"><div v-for="op in unit.operations" :key="op.id" class="fact"><b>{{op.sequence}} - {{op.operation_name}}</b><span>实际工时 {{Number(op.actual_labor_minutes||0).toFixed(1)}} 分钟</span><small v-for="x in op.labor_sessions" :key="x.id">人员 {{x.employee_legacy_id}} · {{x.actual_labor_minutes}} 分钟</small></div></el-tab-pane><el-tab-pane label="质量" name="quality"><div v-for="op in unit.operations" :key="op.id" class="fact"><b>{{op.operation_name}}</b><span>{{op.quality_inspections.length?op.quality_inspections[0].result:'暂无质检事实'}}</span></div></el-tab-pane><el-tab-pane label="库存流转" name="inventory"><el-empty description="按正式工序产出、生产入库和内部领用流水展示"/></el-tab-pane></el-tabs></div></el-drawer>
  </div>
</template>
<script>
import { getProductionExecutionMonitor,listProductionWorkOrderUnits,getProductionUnit } from '../../../api/erp/production'
export default{name:'ProductionExecutionMonitor',data:()=>({loading:false,rows:[],total:0,page:1,stats:{},filters:{planned_date:'',keyword:'',status:''},selected:null,units:[],drawer:false,unit:null,tab:'material',statCards:[{key:'work_orders',label:'在制工单数',unit:'单'},{key:'operations',label:'在制工序数',unit:'道'},{key:'active_units',label:'在制设备数',unit:'台'},{key:'units',label:'生产单元数',unit:'台'}]}),created(){this.load()},methods:{async load(){this.loading=true;try{const r=await getProductionExecutionMonitor({...this.filters,page:this.page,per_page:10});this.rows=r.data.data||[];this.total=r.data.meta.total;this.stats=r.data.stats||{}}catch(e){this.$message.error(e.userMessage||'加载失败')}finally{this.loading=false}},reset(){this.filters={planned_date:'',keyword:'',status:''};this.page=1;this.load()},status(v){return({RELEASED:'已发布',IN_PROGRESS:'执行中',COMPLETED:'已完成',WAIT_CLAIM:'待接单',WAIT_MATERIAL:'待齐套',READY:'待开工'})[v]||v},async openOrder(row){this.selected=row;const r=await listProductionWorkOrderUnits(row.id);this.units=r.data.data||[]},async openUnit(row){const r=await getProductionUnit(row.id);this.unit=r.data.data;this.tab='material';this.drawer=true}}}
</script>
<style scoped>
.monitor-page{padding:20px}.page-heading{display:flex;justify-content:space-between;margin-bottom:16px}.eyebrow{color:#059669;font-size:13px;margin:0}.page-heading h1{margin:6px 0;font-size:24px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats>div,.filter-card,.table-card{background:#fff;border:1px solid #e5e7eb;border-radius:4px}.stats>div{padding:18px}.stats span{display:block;color:#64748b;font-size:13px}.stats strong{font-size:30px;color:#078447;margin-right:6px}.filter-card{display:flex;gap:10px;padding:14px;margin:12px 0}.filter-card .el-input{max-width:270px}.table-card{padding:14px;margin-bottom:12px}.table-card h3{margin:0 0 12px}.el-table small{display:block;color:#64748b;margin-top:4px}.table-footer{display:flex;justify-content:space-between;align-items:center;padding-top:12px}.drawer-body{padding:0 20px}.fact{display:flex;flex-direction:column;gap:8px;border-bottom:1px solid #eee;padding:12px 0}.fact small{color:#64748b}@media(max-width:1100px){.stats{grid-template-columns:repeat(2,1fr)}.filter-card{flex-wrap:wrap}}
</style>
