<template>
  <section class="production-page" v-loading="loading">
    <div class="page-heading"><div><p class="eyebrow">生产管理 / 生产基础 / 工艺路线</p><h1>{{ title }}</h1><p>路线绑定正式产出物料；版本号由系统维护</p></div><el-button @click="$router.push('/production/routings')">返回列表</el-button></div>
    <section class="form-card"><el-form ref="form" :model="form" :rules="rules" label-position="top">
      <div class="form-grid">
        <el-form-item label="路线编码"><el-input v-model="form.routing_no" disabled /></el-form-item>
        <el-form-item label="路线名称" prop="routing_name"><el-input v-model="form.routing_name" :disabled="viewOnly" /></el-form-item>
        <el-form-item label="产出物料" prop="output_item_id"><el-select v-model="form.output_item_id" :disabled="viewOnly" filterable remote :remote-method="v=>searchOption('items',v)" style="width:100%"><el-option v-for="i in options.items" :key="i.id" :label="`${i.item_code} / ${i.item_name}`" :value="i.id" /></el-select></el-form-item>
        <el-form-item label="版本（系统递增）"><el-input :value="`V${form.version}`" disabled /></el-form-item>
        <el-form-item label="关联产品（可选）"><el-select v-model="form.product_id" :disabled="viewOnly" clearable filterable remote :remote-method="v=>searchOption('products',v)" style="width:100%"><el-option v-for="i in options.products" :key="i.id" :label="`${i.product_code} / ${i.product_name}`" :value="i.id" /></el-select></el-form-item>
        <el-form-item label="关联 SKU（可选）"><el-select v-model="form.sku_id" :disabled="viewOnly" clearable filterable remote :remote-method="v=>searchOption('skus',v)" style="width:100%" @change="onSku"><el-option v-for="i in options.skus" :key="i.id" :label="`${i.sku_code} / ${i.sku_name}`" :value="i.id" /></el-select></el-form-item>
        <el-form-item label="状态"><el-input :value="statusText(form.status)" disabled /></el-form-item><el-form-item label="是否默认"><el-input :value="form.is_default?'是':'否'" disabled /></el-form-item>
      </div>
      <div class="sub-heading"><h2>路线工序</h2><el-button v-if="!viewOnly" type="success" plain @click="addOperation">添加工序</el-button></div>
      <el-table :data="form.operations" border row-key="sequence"><el-table-column label="顺序" width="110"><template slot-scope="s"><el-input-number v-model="s.row.sequence" :disabled="viewOnly" :min="1" :step="10" size="small" /></template></el-table-column><el-table-column label="工序" min-width="250"><template slot-scope="s"><el-select v-model="s.row.operation_id" :disabled="viewOnly" filterable remote :remote-method="v=>searchOption('operations',v)" style="width:100%"><el-option v-for="o in options.operations" :key="o.id" :label="`${o.operation_no} / ${o.operation_name}`" :value="o.id" /></el-select></template></el-table-column><el-table-column label="关键工序" width="100"><template slot-scope="s"><el-switch v-model="s.row.is_key_operation" :disabled="viewOnly" /></template></el-table-column><el-table-column label="必要参数" min-width="190"><template slot-scope="s"><el-input v-model="s.row.parameters_text" :disabled="viewOnly" placeholder="例如：温度=180℃" /></template></el-table-column><el-table-column label="备注" min-width="200"><template slot-scope="s"><el-input v-model="s.row.remark" :disabled="viewOnly" type="textarea" autosize /></template></el-table-column><el-table-column v-if="!viewOnly" label="操作" width="140"><template slot-scope="s"><el-button type="text" :disabled="s.$index===0" @click="move(s.$index,-1)">上移</el-button><el-button type="text" @click="remove(s.$index)">删除</el-button></template></el-table-column></el-table>
      <el-form-item label="备注" style="margin-top:18px"><el-input v-model="form.remark" :disabled="viewOnly" type="textarea" :rows="3" /></el-form-item><div v-if="!viewOnly" class="form-actions"><el-button @click="$router.push('/production/routings')">取消</el-button><el-button type="success" @click="save">保存草稿</el-button></div>
    </el-form></section>
  </section>
</template>
<script>
import { reserveProductionNumber, searchProductionOptions, getProductionRouting, createProductionRouting, updateProductionRouting } from '../../../api/erp/production'
const uuid=()=>window.crypto&&window.crypto.randomUUID?window.crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})
export default { name:'ProductionRoutingForm', data:()=>({loading:false,sessionId:'',reservationToken:'',options:{operations:[],items:[],products:[],skus:[]},form:{routing_no:'正在生成…',routing_name:'',output_item_id:null,product_id:null,sku_id:null,version:1,status:'draft',is_default:false,remark:'',business_version:1,operations:[]},rules:{routing_name:[{required:true,message:'请输入路线名称',trigger:'blur'}],output_item_id:[{required:true,message:'请选择产出物料',trigger:'change'}]}}), computed:{id(){return this.$route.params.id},viewOnly(){return !!this.id&&!this.$route.path.endsWith('/edit')},title(){return this.id?(this.viewOnly?'查看工艺路线':'编辑工艺路线'):'新增工艺路线'}}, async created(){await this.loadOptions();this.id?this.load():this.reserve()}, methods:{
  statusText(v){return({draft:'草稿',active:'已生效',retired:'已退役',disabled:'已退役'})[v]||'草稿'},
  async searchOption(type,keyword=''){const r=await searchProductionOptions(type,{keyword,per_page:20});this.$set(this.options,type,r.data.data||[])},
  async loadOptions(){try{await Promise.all(['operations','items','products','skus'].map(type=>this.searchOption(type)))}catch(e){this.$message.error(e.userMessage||'生产基础选项加载失败')}},
  onSku(id){const sku=this.options.skus.find(x=>x.id===id);this.form.product_id=sku?sku.product_id:null},
  async reserve(){this.loading=true;this.sessionId=uuid();try{const r=await reserveProductionNumber('routing',this.sessionId,this.$route.path);this.form.routing_no=r.data.data.document_no;this.reservationToken=r.data.data.reservation_token;this.addOperation()}catch(e){this.$message.error(e.userMessage||'编号生成失败')}finally{this.loading=false}},
  async load(){this.loading=true;try{const r=await getProductionRouting(this.id);const data=r.data.data;data.operations=(data.operations||[]).map(x=>({...x,parameters_text:x.parameters&&x.parameters.text||''}));this.form={...this.form,...data};[['items',data.output_item],['products',data.product],['skus',data.sku]].forEach(([type,row])=>{if(row&&!this.options[type].some(x=>x.id===row.id))this.options[type].push(row)})}catch(e){this.$message.error(e.userMessage||'路线加载失败')}finally{this.loading=false}},
  addOperation(){this.form.operations.push({operation_id:null,sequence:(this.form.operations.length+1)*10,is_key_operation:false,parameters_text:'',remark:''})}, remove(i){this.form.operations.splice(i,1)}, move(i,d){const j=i+d;if(j<0||j>=this.form.operations.length)return;const a=this.form.operations[i];this.form.operations.splice(i,1);this.form.operations.splice(j,0,a);this.form.operations.forEach((r,k)=>r.sequence=(k+1)*10)},
  save(){this.$refs.form.validate(async ok=>{if(!ok)return;if(!this.form.operations.length||this.form.operations.some(x=>!x.operation_id))return this.$message.warning('请完整选择至少一道工序');this.loading=true;const operations=this.form.operations.map(x=>({operation_id:x.operation_id,sequence:x.sequence,is_key_operation:x.is_key_operation,parameters:x.parameters_text?{text:x.parameters_text}:null,remark:x.remark||null}));try{const common={client_command_id:`routing-${this.id?'update':'create'}-${this.id||this.sessionId}-${Date.now()}`,routing_name:this.form.routing_name,output_item_id:this.form.output_item_id,product_id:this.form.product_id,sku_id:this.form.sku_id,remark:this.form.remark,operations};if(this.id)await updateProductionRouting(this.id,{...common,expected_version:this.form.business_version});else await createProductionRouting({...common,creation_session_id:this.sessionId,reservation_token:this.reservationToken});this.$message.success('工艺路线草稿已保存');this.$router.push('/production/routings')}catch(e){this.$message.error(e.userMessage||'保存失败')}finally{this.loading=false}})}
} }
</script>
<style scoped src="./production-master.css"></style>
<style scoped>.sub-heading{display:flex;align-items:center;justify-content:space-between;margin:10px 0 14px}.sub-heading h2{margin:0;font-size:17px;color:#24384f}.form-card small,.table-card small{display:block;color:#8390a0}</style>
