<template>
  <section class="production-page" v-loading="loading">
    <div class="page-heading"><div><p class="eyebrow">生产管理 / 生产基础</p><h1>工艺路线</h1><p>同一业务路线使用固定编码和连续版本，历史版本永久保留</p></div><el-button v-if="$can('production.routing.create')" type="success" @click="$router.push('/production/routings/new')">新增工艺路线</el-button></div>
    <section class="filter-card"><div class="filter-grid"><label><span>路线编码 / 名称</span><el-input v-model="filters.keyword" clearable placeholder="请输入路线编码或名称" /></label><label><span>状态</span><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option label="草稿" value="draft" /><el-option label="已生效" value="active" /><el-option label="已退役" value="retired" /></el-select></label></div><div class="filter-actions"><el-button @click="reset">重置</el-button><el-button type="success" @click="search">查询</el-button></div></section>
    <p class="result-count">共 {{ total }} 条</p>
    <section class="table-card"><el-table :data="rows" border><el-table-column prop="routing_no" label="路线编码" min-width="150" /><el-table-column prop="routing_name" label="路线名称" min-width="170" /><el-table-column label="产出物料" min-width="190"><template slot-scope="s"><span class="wrap-text">{{ s.row.output_item&&s.row.output_item.item_name||'-' }}</span><small>{{ s.row.output_item&&s.row.output_item.item_code||'' }}</small></template></el-table-column><el-table-column label="版本" width="70"><template slot-scope="s">V{{ s.row.version }}</template></el-table-column><el-table-column prop="operations_count" label="工序数" width="76" /><el-table-column label="状态" width="90"><template slot-scope="s"><el-tag size="mini" :type="s.row.status==='active'?'success':s.row.status==='retired'?'info':''">{{ statusText(s.row.status) }}</el-tag></template></el-table-column><el-table-column label="默认" width="65"><template slot-scope="s">{{ s.row.is_default?'是':'否' }}</template></el-table-column><el-table-column label="操作" width="310"><template slot-scope="s"><div class="inline-actions"><el-button type="text" @click="$router.push(`/production/routings/${s.row.id}`)">查看</el-button><el-button v-if="s.row.status==='draft'&&$can('production.routing.edit')" type="text" @click="$router.push(`/production/routings/${s.row.id}/edit`)">编辑</el-button><el-button v-if="s.row.status==='draft'&&$can('production.routing.activate')" type="text" @click="activate(s.row)">生效</el-button><el-button v-if="s.row.status==='active'&&!s.row.is_default&&$can('production.routing.default')" type="text" @click="setDefault(s.row)">设为默认</el-button><el-button v-if="$can('production.routing.create')" type="text" @click="copyVersion(s.row)">复制新版本</el-button><el-button v-if="s.row.status==='active'&&$can('production.routing.activate')" type="text" class="danger-action" @click="retire(s.row)">退役</el-button></div></template></el-table-column></el-table><div class="table-footer"><span>共 {{ total }} 条</span><el-pagination background layout="prev, pager, next" :current-page="page" :page-size="20" :total="total" @current-change="v=>{page=v;load()}" /></div></section>
  </section>
</template>
<script>
import { listProductionRoutings, activateProductionRouting, setDefaultProductionRouting, copyProductionRouting, retireProductionRouting } from '../../../api/erp/production'
export default { name: 'ProductionRoutingList', data: () => ({ loading: false, rows: [], total: 0, page: 1, filters: { keyword: '', status: '' } }), created () { this.load() }, methods: {
  statusText (v) { return ({ draft: '草稿', active: '已生效', retired: '已退役', disabled: '已退役' })[v] || '未知' },
  async load () { this.loading = true; try { const r = await listProductionRoutings({ ...this.filters, page: this.page, per_page: 20 }); this.rows = r.data.data || []; this.total = r.data.total || 0 } catch (e) { this.$message.error(e.userMessage || '工艺路线加载失败') } finally { this.loading = false } },
  search () { this.page = 1; this.load() }, reset () { this.filters = { keyword: '', status: '' }; this.search() },
  async activate (row) { try { await this.$confirm('生效后路线结构不可直接修改，确认继续？', '生效工艺路线', { type: 'warning' }); await activateProductionRouting(row.id, { client_command_id: `routing-activate-${row.id}-${Date.now()}`, expected_version: row.business_version }); this.$message.success('工艺路线已生效'); this.load() } catch (e) { if (e !== 'cancel' && e !== 'close') this.$message.error(e.userMessage || '生效失败') } },
  async setDefault (row) { try { await this.$confirm('确认将该版本设为当前产出物料的默认生效路线？', '设置默认路线'); await setDefaultProductionRouting(row.id, { client_command_id: `routing-default-${row.id}-${Date.now()}`, expected_version: row.business_version }); this.$message.success('默认路线已更新'); this.load() } catch (e) { if (e !== 'cancel' && e !== 'close') this.$message.error(e.userMessage || '设置失败') } },
  async copyVersion (row) { try { await this.$confirm(`复制 ${row.routing_no} V${row.version} 为下一版本？`, '复制新版本'); const r = await copyProductionRouting(row.id, { client_command_id: `routing-copy-${row.id}-${Date.now()}` }); this.$message.success(`已生成 ${r.data.data.routing_no} V${r.data.data.version}`); this.load() } catch (e) { if (e !== 'cancel' && e !== 'close') this.$message.error(e.userMessage || '复制失败') } },
  async retire (row) { try { await this.$confirm('退役后不能再被新工单选用，历史工单不受影响。', '退役工艺路线', { type: 'warning' }); await retireProductionRouting(row.id, { client_command_id: `routing-retire-${row.id}-${Date.now()}`, expected_version: row.business_version }); this.$message.success('工艺路线已退役'); this.load() } catch (e) { if (e !== 'cancel' && e !== 'close') this.$message.error(e.userMessage || '退役失败') } }
} }
</script>
<style scoped src="./production-master.css"></style>
<style scoped>.inline-actions{display:flex;align-items:center;white-space:nowrap}.danger-action{color:#d9534f}.wrap-text{white-space:normal;word-break:break-word}</style>
