<template>
  <div class="finance-account-page">
    <div class="finance-page-title">
      <div><h1>资金账户</h1><p>管理企业的资金账户信息，支持账户的新增、编辑、启用/停用等操作。</p></div>
      <el-button v-if="$can('finance.account.manage')" class="finance-primary" type="success" icon="el-icon-plus" @click="openCreate">新增资金账户</el-button>
    </div>
    <section class="finance-filter account-filter">
      <label>账户编号<el-input v-model.trim="query.keyword" placeholder="请输入账户编号" clearable @keyup.enter.native="search" /></label>
      <label>账户名称<el-input v-model.trim="query.account_name" placeholder="请输入账户名称" clearable @keyup.enter.native="search" /></label>
      <label>账户类型<el-select v-model="query.account_type" clearable placeholder="请选择账户类型"><el-option v-for="o in types" :key="o.value" :label="o.label" :value="o.value" /></el-select></label>
      <label>币种<el-select v-model="query.currency" clearable placeholder="请选择币种"><el-option v-for="c in currencies" :key="c.currency_code" :label="`${c.currency_code} · ${c.currency_name}`" :value="c.currency_code" /></el-select></label>
      <label>状态<el-select v-model="query.status" clearable placeholder="请选择状态"><el-option label="启用" value="enabled" /><el-option label="停用" value="disabled" /></el-select></label>
      <div class="filter-actions"><el-button class="finance-primary" type="success" @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
    </section>
    <section class="finance-table-card">
      <el-table v-loading="loading" :data="rows" border size="small" class="account-table">
        <el-table-column prop="account_no" label="账户编号" min-width="140" />
        <el-table-column prop="account_name" label="账户名称" min-width="145" />
        <el-table-column label="账户类型" width="96"><template slot-scope="{row}">{{ typeLabel(row.account_type) }}</template></el-table-column>
        <el-table-column prop="bank_name" label="开户行" min-width="220"><template slot-scope="{row}">{{ row.bank_name || '--' }}</template></el-table-column>
        <el-table-column prop="bank_account_no" label="银行账号" min-width="160"><template slot-scope="{row}">{{ row.bank_account_no || '--' }}</template></el-table-column>
        <el-table-column prop="currency" label="币种" width="65" />
        <el-table-column label="状态" width="74" align="center"><template slot-scope="{row}"><el-tag :type="row.status==='enabled'?'success':'danger'" size="mini">{{ row.status==='enabled'?'启用':'停用' }}</el-tag></template></el-table-column>
        <el-table-column prop="sort" label="排序" width="64" align="center"><template slot-scope="{row}">{{ row.sort || '--' }}</template></el-table-column>
        <el-table-column label="更新时间" min-width="150"><template slot-scope="{row}">{{formatDateTime(row.updated_at)}}</template></el-table-column>
        <el-table-column label="操作" width="132" align="center"><template slot-scope="{row}"><el-button v-if="$can('finance.account.manage')" type="text" @click="openEdit(row)">编辑</el-button><el-button v-if="$can('finance.account.manage')" :class="row.status==='enabled'?'danger-text':'success-text'" type="text" @click="toggle(row)">{{ row.status==='enabled'?'停用':'启用' }}</el-button></template></el-table-column>
      </el-table>
      <el-pagination background layout="total, sizes, prev, pager, next, jumper" :current-page="page" :page-size="perPage" :page-sizes="[10,20,50,100]" :total="total" @current-change="p=>{page=p;load()}" @size-change="s=>{perPage=s;page=1;load()}" />
    </section>
    <el-dialog :title="form.id?'编辑资金账户':'新增资金账户'" :visible.sync="dialog" width="620px" :close-on-click-modal="false">
      <el-form ref="form" :model="form" :rules="rules" label-width="105px">
        <el-row :gutter="18"><el-col :span="12"><el-form-item label="账户编号"><el-input v-model="form.account_no" disabled /></el-form-item></el-col><el-col :span="12"><el-form-item label="账户名称" prop="account_name"><el-input v-model.trim="form.account_name" /></el-form-item></el-col></el-row>
        <el-row :gutter="18"><el-col :span="12"><el-form-item label="账户类型" prop="account_type"><el-select v-model="form.account_type"><el-option v-for="o in types" :key="o.value" :label="o.label" :value="o.value" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="币种" prop="currency"><el-select v-model="form.currency" :disabled="Boolean(form.movements_exists)"><el-option v-for="c in currencies" :key="c.currency_code" :label="`${c.currency_code} · ${c.currency_name}`" :value="c.currency_code" /></el-select><small v-if="form.movements_exists" class="currency-lock">已产生资金流水，币种不可变更；请新建对应币种账户。</small></el-form-item></el-col></el-row>
        <el-row :gutter="18"><el-col :span="12"><el-form-item label="开户行/平台"><el-input v-model.trim="form.bank_name" /></el-form-item></el-col><el-col :span="12"><el-form-item label="银行账号"><el-input v-model.trim="form.bank_account_no" /></el-form-item></el-col></el-row>
        <el-form-item label="备注"><el-input v-model.trim="form.remark" type="textarea" :rows="3" maxlength="1000" show-word-limit /></el-form-item>
      </el-form>
      <span slot="footer"><el-button @click="dialog=false">取消</el-button><el-button class="finance-primary" type="success" :loading="saving" @click="save">保存</el-button></span>
    </el-dialog>
  </div>
</template>
<script>
import { listFinanceAccounts, createFinanceAccount, updateFinanceAccount, setFinanceAccountStatus, listFinanceCurrencies } from '../../../api/erp/finance'
import { reserveForCreatePage, clearCreatePageReservation } from '../../../utils/documentNumberReservation'
const blank=()=>({id:null,account_no:'',account_name:'',account_type:'bank',bank_name:'',bank_account_no:'',currency:'CNY',remark:''})
export default { data:()=>({loading:false,saving:false,dialog:false,rows:[],currencies:[],page:1,perPage:10,total:0,query:{keyword:'',account_name:'',account_type:'',currency:'',status:''},form:blank(),reservation:null,types:[{label:'基本账户',value:'bank'},{label:'现金账户',value:'cash'},{label:'支付平台',value:'platform'},{label:'其他资金账户',value:'other'}],rules:{account_name:[{required:true,message:'请输入账户名称',trigger:'blur'}],account_type:[{required:true,message:'请选择账户类型',trigger:'change'}],currency:[{required:true,message:'请选择币种',trigger:'change'}]}}),created(){this.bootstrap()},methods:{async bootstrap(){try{const r=await listFinanceCurrencies({per_page:100,status:'enabled'});this.currencies=r.data.data||[]}catch(e){this.$message.error(e.userMessage||'币种加载失败')}this.load()},typeLabel(v){return this.types.find(x=>x.value===v)?.label||v},formatDateTime(v){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return v;const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`},async load(){this.loading=true;try{const r=await listFinanceAccounts({...this.query,page:this.page,per_page:this.perPage});this.rows=r.data.data||[];this.total=Number(r.data.total||0)}catch(e){this.$message.error(e.userMessage||'资金账户加载失败')}finally{this.loading=false}},search(){this.page=1;this.load()},reset(){this.query={keyword:'',account_name:'',account_type:'',currency:'',status:''};this.search()},async openCreate(){this.form=blank();this.dialog=true;try{this.reservation=await reserveForCreatePage('finance_account','/finance/accounts#create');this.form.account_no=this.reservation.document_no}catch(e){this.dialog=false;this.$message.error(e.userMessage||'账户编号生成失败')}},openEdit(row){this.reservation=null;this.form={...blank(),...row};this.dialog=true},save(){this.$refs.form.validate(async ok=>{if(!ok)return;this.saving=true;try{if(this.form.id)await updateFinanceAccount(this.form.id,this.form);else{await createFinanceAccount({...this.form,reservation_token:this.reservation.reservation_token,creation_session_id:this.reservation.creation_session_id});clearCreatePageReservation(this.reservation)}this.$message.success('保存成功');this.dialog=false;await this.load()}catch(e){this.$message.error(e.userMessage||'保存失败')}finally{this.saving=false}})},async toggle(row){try{await this.$confirm(`确认${row.status==='enabled'?'停用':'启用'}账户“${row.account_name}”？`,'状态确认',{type:'warning'});await setFinanceAccountStatus(row.id,row.status==='enabled'?'disabled':'enabled');this.$message.success('状态已更新');await this.load()}catch(e){if(e!=='cancel')this.$message.error(e.userMessage||'操作失败')}}}}
</script>
<style scoped>
.finance-account-page{padding:26px 26px 40px;background:#f7f9fb;min-height:calc(100vh - 64px);box-sizing:border-box;color:#202938}.finance-page-title{display:flex;align-items:flex-start;justify-content:space-between;margin:0 0 20px}.finance-page-title h1{margin:0 0 7px;font-size:27px;line-height:1.25;color:#151d2b}.finance-page-title p{margin:0;font-size:14px;color:#728095}.finance-primary{background:#008c4a;border-color:#008c4a}.finance-filter,.finance-table-card{background:#fff;border:1px solid #e0e6ee;border-radius:6px;box-shadow:0 2px 6px rgba(16,24,40,.04)}.finance-filter{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:18px 50px;padding:23px 25px 20px;margin-bottom:10px}.finance-filter label{display:block;font-size:14px;font-weight:600;color:#343d4a}.finance-filter .el-input,.finance-filter .el-select{width:100%;display:block;margin-top:7px}.filter-actions{display:flex;align-items:flex-end;gap:16px}.filter-actions .el-button{min-width:84px}.finance-table-card{padding:14px 14px 16px}.account-table{width:100%}.finance-table-card >>> .el-table th{height:45px;background:#f6f8fa;color:#2e3746;font-weight:600}.finance-table-card >>> .el-table td{height:45px;color:#303946}.finance-table-card >>> .el-table--border:after,.finance-table-card >>> .el-table--group:after{background:#e8edf3}.el-pagination{margin:18px 4px 0;text-align:right}.danger-text{color:#f04438}.success-text{color:#079455}@media(max-width:1180px){.finance-filter{grid-template-columns:repeat(3,minmax(170px,1fr));gap:16px 24px}}@media(max-width:820px){.finance-account-page{padding:18px 14px}.finance-page-title{gap:14px}.finance-filter{grid-template-columns:repeat(2,minmax(0,1fr));padding:18px}.finance-table-card{overflow-x:auto}.finance-table-card .account-table{min-width:1080px}}@media(max-width:560px){.finance-page-title{flex-direction:column}.finance-filter{grid-template-columns:1fr}.filter-actions{align-items:center}}
</style>
