<template>
  <div class="cash-list-page">
    <div class="cash-list-heading"><h1>{{ title }}管理</h1><p>{{ direction==='receipt' ? '管理企业收款单据，支持收款确认、核销及状态跟踪' : '管理企业付款单据，支持付款确认、核销及状态跟踪' }}</p></div>
    <el-button v-if="$can(createPermission)" class="new-cash finance-primary" type="success" icon="el-icon-plus" @click="$router.push(basePath+'/create')">新增{{ title }}</el-button>
    <section class="cash-filter">
      <label>{{ title }}单号<el-input v-model.trim="query.keyword" clearable :placeholder="`请输入${title}单号`" @keyup.enter.native="search" /></label>
      <label>客户/交易对手<el-input v-model.trim="query.party_keyword" clearable placeholder="请输入客户/交易对手" @keyup.enter.native="search"><i slot="suffix" class="el-icon-search" /></el-input></label>
      <label>资金账户<el-select v-model="query.finance_account_id" clearable placeholder="请选择资金账户"><el-option v-for="a in accounts" :key="a.id" :label="a.account_name" :value="a.id" /></el-select></label>
      <label>状态<el-select v-model="query.status" clearable placeholder="请选择状态"><el-option label="草稿" value="draft" /><el-option label="已确认" value="confirmed" /><el-option label="已作废" value="voided" /></el-select></label>
      <label class="date-filter">{{ title }}日期范围<el-date-picker v-model="query.date_range" type="daterange" value-format="yyyy-MM-dd" range-separator="~" start-placeholder="开始日期" end-placeholder="结束日期" /></label>
      <div class="cash-filter-actions"><el-button class="finance-primary" type="success" @click="search">查询</el-button><el-button @click="reset">重置</el-button></div>
    </section>
    <section ref="cashTableCard" class="cash-table-card">
      <el-table v-loading="loading" :data="rows" border size="small" class="cash-table">
        <el-table-column prop="document_no" :label="title+'单号'" min-width="136"><template slot-scope="{row}"><a @click="view(row)">{{row.document_no}}</a></template></el-table-column>
        <el-table-column :label="title+'日期'" width="110"><template slot-scope="{row}">{{dateText(row.business_date)}}</template></el-table-column>
        <el-table-column prop="party_name_snapshot" label="交易对手" min-width="168" />
        <el-table-column prop="account.account_name" label="资金账户" min-width="175" />
        <el-table-column prop="currency" label="币种" width="66" />
        <el-table-column label="实收金额" width="112" align="right"><template slot-scope="{row}">{{money(row.amount)}}</template></el-table-column>
        <el-table-column label="已核销" width="105" align="right"><template slot-scope="{row}">{{money(row.allocated_amount)}}</template></el-table-column>
        <el-table-column label="未核销" width="105" align="right"><template slot-scope="{row}">{{money(row.unallocated_amount)}}</template></el-table-column>
        <el-table-column prop="payment_method" :label="title+'方式'" min-width="105" />
        <el-table-column label="状态" width="100" align="center"><template slot-scope="{row}"><el-tag :class="'cash-status '+row.status" :type="tagType(row.status)" size="mini">{{statusLabel(row)}}</el-tag></template></el-table-column>
        <el-table-column prop="operator_name" label="经办人" width="86"><template slot-scope="{row}">{{row.operator_name||'—'}}</template></el-table-column>
        <el-table-column label="操作" width="146"><template slot-scope="{row}"><el-button type="text" @click="view(row)">查看</el-button><el-button v-if="row.status==='draft'&&$can(confirmPermission)" type="text" @click="confirm(row)">确认</el-button><el-button v-if="row.status==='confirmed'&&Number(row.unallocated_amount)>0&&$can('finance.allocation.create')" type="text" @click="openAllocation(row)">核销</el-button><el-button v-if="row.status==='confirmed'&&$can(voidPermission)" class="danger" type="text" @click="voidDoc(row)">作废</el-button></template></el-table-column>
      </el-table>
      <el-pagination background layout="total, prev, pager, next, sizes, jumper" :current-page="page" :page-size="perPage" :page-sizes="[10,20,50,100]" :total="total" @current-change="p=>{page=p;load()}" @size-change="s=>{perPage=s;page=1;load()}" />
    </section>
  </div>
</template>
<script>
import { listCashDocuments, confirmCashDocument, voidCashDocument, listFinanceAccounts } from '../../../api/erp/finance'
export default { props:{direction:{type:String,required:true}},data:()=>({loading:false,rows:[],accounts:[],page:1,perPage:10,total:0,query:{keyword:'',party_keyword:'',finance_account_id:'',status:'',date_range:[]}}),computed:{title(){return this.direction==='receipt'?'收款':'付款'},basePath(){return this.direction==='receipt'?'/finance/receipts':'/finance/payments'},createPermission(){return `finance.${this.direction}.create`},confirmPermission(){return `finance.${this.direction}.confirm`},voidPermission(){return `finance.${this.direction}.void`}},watch:{direction(){this.page=1;this.load()}},created(){this.load();this.loadAccounts()},methods:{money(v){return Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4})},dateText(v){return String(v||'').slice(0,10)||'—'},tagType(v){return v==='confirmed'?'success':v==='voided'?'danger':'warning'},statusLabel(row){if(row.status==='voided')return'已作废';if(row.status==='draft')return'草稿';return Number(row.unallocated_amount)===0?'已全部核销':Number(row.allocated_amount)>0?'已部分核销':'已确认'},resetTableScroll(){this.$nextTick(()=>{const card=this.$refs.cashTableCard;if(!card)return;card.scrollLeft=0;const body=card.querySelector('.el-table__body-wrapper');if(body)body.scrollLeft=0})},async loadAccounts(){try{const r=await listFinanceAccounts({status:'enabled',page:1,per_page:100});this.accounts=r.data.data||[]}catch(e){}},async load(){this.loading=true;try{const q={keyword:this.query.keyword,party_keyword:this.query.party_keyword,finance_account_id:this.query.finance_account_id,status:this.query.status,business_date_start:this.query.date_range?.[0]||'',business_date_end:this.query.date_range?.[1]||'',page:this.page,per_page:this.perPage};const r=await listCashDocuments(this.direction,q);this.rows=r.data.data||[];this.total=Number(r.data.total||0);this.resetTableScroll()}catch(e){this.$message.error(e.userMessage||'列表加载失败')}finally{this.loading=false}},search(){this.page=1;this.load()},reset(){this.query={keyword:'',party_keyword:'',finance_account_id:'',status:'',date_range:[]};this.search()},view(row){this.$router.push(`${this.basePath}/${row.id}`)},openAllocation(row){this.$router.push({path:`/finance/allocations/${row.id}`,query:{from:'cash-list'}})},async confirm(row){try{await this.$confirm(`确认${this.title}单 ${row.document_no}？确认后金额不可编辑。`,'确认资金事实',{type:'warning'});await confirmCashDocument(row.id);this.$message.success('已确认');await this.load()}catch(e){if(e!=='cancel')this.$message.error(e.userMessage||'确认失败')}},async voidDoc(row){try{const {value}=await this.$prompt('作废后不删除历史事实，请填写作废原因','作废确认',{inputValidator:v=>!!String(v||'').trim()||'原因必填'});await voidCashDocument(row.id,value);this.$message.success('已作废');await this.load()}catch(e){if(e!=='cancel')this.$message.error(e.userMessage||'作废失败')}}}}
</script>
<style scoped>
.cash-list-page{position:relative;padding:22px 24px 36px;background:#fff;min-height:calc(100vh - 64px);box-sizing:border-box;color:#172033}.cash-list-heading{display:flex;align-items:baseline;gap:25px;margin:0 0 20px}.cash-list-heading h1{font-size:27px;line-height:1;margin:0;font-weight:700}.cash-list-heading p{margin:0;color:#69778a;font-size:14px}.finance-primary{background:#008c4a;border-color:#008c4a}.new-cash{position:absolute;right:24px;top:18px;min-width:108px}.cash-filter{border:1px solid #dfe5ec;border-radius:5px;background:#fff;padding:24px 20px 22px;display:grid;grid-template-columns:repeat(4,minmax(170px,1fr));gap:22px 30px}.cash-filter label{font-size:14px;font-weight:600;color:#313b48}.cash-filter .el-input,.cash-filter .el-select,.cash-filter .el-date-editor{width:100%;display:block;margin-top:8px}.cash-filter .el-icon-search{padding:0 8px;line-height:38px;color:#63748a}.date-filter{grid-column:1/span 1}.cash-filter-actions{grid-column:4;display:flex;align-items:end;justify-content:flex-end;gap:14px}.cash-filter-actions .el-button{min-width:84px}.cash-table-card{margin-top:14px}.cash-table-card >>> .el-table th{height:47px;background:#f7f9fb;color:#2d3745;font-weight:600}.cash-table-card >>> .el-table td{height:46px}.cash-table-card >>> .el-table a{color:#1677ff;cursor:pointer;font-weight:500}.cash-status{border:0}.danger{color:#ed4b4b}.el-pagination{margin:24px 14px 0;text-align:right}@media(max-width:1200px){.cash-filter{grid-template-columns:repeat(3,minmax(170px,1fr))}.cash-filter-actions{grid-column:3}}@media(max-width:820px){.cash-list-page{padding:18px 14px}.cash-list-heading{padding-right:120px;display:block}.cash-list-heading h1{margin-bottom:8px}.new-cash{right:14px;top:18px}.cash-filter{grid-template-columns:repeat(2,minmax(0,1fr));padding:18px}.cash-filter-actions{grid-column:2}.cash-table-card{overflow-x:auto}.cash-table{min-width:1450px}}@media(max-width:560px){.cash-filter{grid-template-columns:1fr}.cash-filter-actions{grid-column:1;justify-content:flex-start}.date-filter{grid-column:auto}}
</style>
