<template>
  <div class="ledger-page">
    <div class="page-head"><div><h1>供应商往来</h1><p>按供应商汇总采购应付、付款、预付款、待退款与进项发票。</p></div><el-button type="success" @click="$router.push('/finance/payables')">查看应付管理</el-button></div>
    <section class="summary-line"><span>应付余额合计 <b>{{ money(summary.current_payable_amount) }}</b></span><span>预付款余额 <b class="green">{{ money(summary.prepayment_balance_amount) }}</b></span><span>待供应商退款 <b class="orange">{{ money(summary.pending_refund_amount) }}</b></span><span>未收票合计 <b class="red">{{ money(summary.unreceived_invoice_amount) }}</b></span></section>
    <section class="filter-card"><el-form inline size="small" class="filter-form"><el-form-item label="供应商"><el-input v-model.trim="filters.supplier_keyword" clearable placeholder="名称 / 编码" @keyup.enter.native="search" /></el-form-item><el-form-item label="业务日期"><el-date-picker v-model="dateRange" type="daterange" value-format="yyyy-MM-dd" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" /></el-form-item><el-form-item label="付款状态"><el-select v-model="filters.payment_status" clearable placeholder="全部"><el-option label="未付款" value="unpaid"/><el-option label="部分付款" value="partial"/><el-option label="已付款" value="paid"/><el-option label="质量冻结" value="frozen"/></el-select></el-form-item><el-form-item label="发票状态"><el-select v-model="filters.invoice_status" clearable placeholder="全部"><el-option label="未收票" value="unreceived"/><el-option label="部分收票" value="partial"/><el-option label="已收票" value="received"/></el-select></el-form-item><el-form-item label="是否有余额"><el-select v-model="filters.has_balance" clearable placeholder="全部"><el-option label="有余额" value="yes"/><el-option label="无余额" value="no"/></el-select></el-form-item><el-form-item><el-button type="success" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></section>
    <section class="table-card"><el-table v-loading="loading" :data="rows" border size="small" class="ledger-table"><el-table-column label="供应商编码" prop="supplier_code" min-width="120"/><el-table-column label="供应商名称" prop="supplier_name" min-width="170"/><money-column label="当前应付" prop="current_payable_amount"/><money-column label="已付款" prop="paid_amount"/><money-column label="未付款" prop="unpaid_amount" strong/><money-column label="预付款余额" prop="prepayment_balance_amount"/><money-column label="待退款" prop="pending_refund_amount"/><money-column label="已收发票" prop="received_invoice_amount"/><money-column label="未收发票" prop="unreceived_invoice_amount"/><money-column label="红冲发票" prop="red_invoice_amount"/><el-table-column label="付款状态" width="90"><template slot-scope="{row}"><el-tag size="mini" :type="paymentTag(row.payment_status)">{{paymentLabel(row.payment_status)}}</el-tag></template></el-table-column><el-table-column label="发票状态" width="90"><template slot-scope="{row}"><el-tag size="mini" :type="invoiceTag(row.invoice_status)">{{invoiceLabel(row.invoice_status)}}</el-tag></template></el-table-column><el-table-column label="财务结算" width="94"><template slot-scope="{row}"><el-tag size="mini" :type="financeTag(row.finance_status)">{{financeLabel(row.finance_status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="112" fixed="right"><template slot-scope="{row}"><el-button type="text" @click="viewDetail(row)">查看往来明细</el-button></template></el-table-column></el-table><el-pagination background layout="total, sizes, prev, pager, next, jumper" :current-page="page" :page-size="perPage" :page-sizes="[10,20,50,100]" :total="total" @current-change="p=>{page=p;load()}" @size-change="s=>{perPage=s;page=1;load()}"/></section>
  </div>
</template>
<script>
import Vue from 'vue'
import { listFinanceSupplierLedgers } from '../../../api/erp/finance'
Vue.component('money-column', { props:['label','prop','strong'], template:'<el-table-column :label="label" min-width="112" align="right"><template slot-scope="{row}"><b v-if="strong" class="money-strong">{{ Number(row[prop] || 0).toLocaleString(\'zh-CN\',{minimumFractionDigits:2,maximumFractionDigits:2}) }}</b><span v-else>{{ Number(row[prop] || 0).toLocaleString(\'zh-CN\',{minimumFractionDigits:2,maximumFractionDigits:2}) }}</span></template></el-table-column>' })
export default {data:()=>({rows:[],loading:false,page:1,perPage:20,total:0,dateRange:[],filters:{supplier_keyword:'',payment_status:'',invoice_status:'',has_balance:''},summary:{}}),created(){this.load()},methods:{money:v=>'¥ '+Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),params(){return {...this.filters,business_date_start:this.dateRange?.[0]||'',business_date_end:this.dateRange?.[1]||'',page:this.page,per_page:this.perPage}},async load(){this.loading=true;try{const r=await listFinanceSupplierLedgers(this.params());this.rows=r.data.data||[];this.total=Number(r.data.total||0);this.summary=r.data.summary||{}}catch(e){this.$message.error(e.userMessage||'供应商往来加载失败')}finally{this.loading=false}},search(){this.page=1;this.load()},reset(){this.filters={supplier_keyword:'',payment_status:'',invoice_status:'',has_balance:''};this.dateRange=[];this.page=1;this.load()},viewDetail(row){this.$router.push({path:'/finance/payables',query:{supplier_id:row.supplier_id}})},paymentLabel(v){return({unpaid:'未付款',partial:'部分付款',paid:'已付款',frozen:'质量冻结',settled:'已结清'})[v]||'—'},paymentTag(v){return({unpaid:'danger',partial:'warning',paid:'success',frozen:'warning',settled:'info'})[v]||'info'},invoiceLabel(v){return({unreceived:'未收票',partial:'部分收票',received:'已收票',not_required:'无需发票'})[v]||'—'},invoiceTag(v){return({unreceived:'danger',partial:'warning',received:'success',not_required:'info'})[v]||'info'},financeLabel(v){return({quality_frozen:'质量冻结',pending_refund:'待退款',settled:'已结清',unclosed:'未结清'})[v]||'—'},financeTag(v){return({quality_frozen:'warning',pending_refund:'danger',settled:'success',unclosed:'info'})[v]||'info'}}}
</script>
<style scoped>
.ledger-page{padding:22px;min-width:0;background:#f5f7fa}.page-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.page-head h1{margin:0;color:#17233d;font-size:24px;line-height:34px}.page-head p{margin:4px 0 0;color:#7b8794;font-size:13px}.summary-line{display:flex;gap:0;background:#fff;border:1px solid #e5eaf1;border-radius:5px;margin-bottom:14px}.summary-line span{padding:14px 26px;border-right:1px solid #edf0f4;color:#64748b;font-size:13px}.summary-line b{margin-left:8px;color:#1f2937;font-size:18px}.summary-line .green{color:#059669}.summary-line .orange{color:#ed8b00}.summary-line .red{color:#e34d59}.filter-card,.table-card{background:#fff;border:1px solid #e5eaf1;border-radius:5px;padding:16px;margin-bottom:14px}.filter-form{display:flex;flex-wrap:wrap;gap:0 8px}.filter-form .el-form-item{margin:0 0 12px}.filter-form .el-input,.filter-form .el-select{width:160px}.filter-form .el-date-editor{width:230px}.table-card{padding:0;overflow:auto}.ledger-table{min-width:1640px}.ledger-table ::v-deep .cell{white-space:normal;overflow:visible;text-overflow:clip;line-height:20px}.money-strong{color:#e34d59}.el-pagination{padding:14px 16px;text-align:right}@media(max-width:980px){.ledger-page{padding:12px}.page-head{align-items:flex-start;gap:10px;flex-direction:column}.summary-line{display:grid;grid-template-columns:1fr 1fr}.summary-line span{border-bottom:1px solid #edf0f4}.filter-form .el-form-item,.filter-form .el-input,.filter-form .el-select,.filter-form .el-date-editor{width:100%}}
</style>
