export const STATUS_LABELS = {
  draft: '草稿',
  unconfirmed: '未确认',
  pending_confirmation: '待正式确认',
  confirmed: '已确认',
  closed: '已关闭',
  cancelled: '已取消',
  changed: '已变更',
  pending: '待处理',
  partial: '部分履约',
  pending_confirm: '待确认',
  approved: '已审核',
  rejected: '已驳回',
  not_required: '无需处理',
  unmatched: '未匹配',
  not_planned: '未计划履约',
  not_entered: '未进入生产',
  physical: '实物发货',
  service: '服务履约',
  no_delivery: '无需发货',
  auxiliary: '辅助录入',
  fee: '费用',
  manual: '手工录入',
  legacy_sync: '历史迁移',
  crm_clue: '线索转单',

  inventory: '库存履约',
  production: '生产履约',
  mixed: '库存+生产',
  non_physical_only: '非实物履约',
  service_only: '服务履约',
  no_delivery_only: '无需发货',
  inventory_reserved_pending: '待库存占用',
  production_pending: '待生产',
  service_fulfilled: '服务已履约',
  no_delivery_closed: '无需发货已关闭',
  reservation_pending: '待库存占用',
  reserved: '已占用',
  fulfilled: '已履约',
  not_started: '未开始',
  not_shipped: '未发货',
  shipped: '已发货',
  open: '待处理',

  create: '创建订单',
  update: '编辑订单',
  submit_confirmation: '提交确认前检查',
  confirm: '正式确认订单',
  delete_draft: '删除订单草稿',

  active: '有效',
  replaced: '已替换',
  deleted: '已删除',

  contract: '合同附件',
  public_attachment: '公共附件',
  customer_agreement: '客户技术协议',
  design_drawing: '设计图纸',
  customer_drawing: '客户图纸',
  technical_agreement: '技术协议',
  configuration_note: '配置说明',
  other: '其他附件',

  matched: '已关联',
  abnormal: '关联异常',

  enabled: '启用',
  disabled: '停用',
  valid: '有效',
  invalid: '无效',
  pending_production_confirmation: '待生产确认',
  production_confirmed: '生产确认完成',
  confirmed_pending_fulfillment: '待履约确认',
  demand_confirmed: '履约需求已确认',
  partially_confirmed: '部分履约需求已确认',
  fulfillment_blocked: '履约确认受阻',

  candidate_submitted: '订单变更已提交审核',
  candidate_rejected: '订单变更已驳回',
  candidate_approved: '订单变更审核通过',
  confirmed_order_change: '正式订单变更',
  confirmed_order_edit: '正式订单直接编辑',
  confirmed_order_change_applied: '正式订单变更已生效',
  production_confirm: '订单生产确认',

  sales_order: '销售订单工单',
  production_plan: '生产计划工单',
  trial: '试制品工单',
  waiting_release: '待下达',
  released: '已下达',
  waiting_accept: '待接单',
  in_progress: '生产中',
  paused: '暂停',
  completed: '生产完成',
  assembled: '总装完成',
  pending_destination: '待选择完工去向',
  pending_inspection: '待交付检验',
  inspecting: '检验中',
  inspection_passed: '检验合格',
  inspection_failed: '检验不合格',
  pending_receipt: '待入库',
  received: '已入库',
  pending_issue: '待领料',
  partially_issued: '部分领料',
  issued: '已领料',
  pending_report: '待报工',
  partially_reported: '部分报工',
  reported: '已报工',
  ready: '待开始',
  accepted: '已接工序',
  skipped: '已跳过',
  transferred: '已移交',
  exception: '异常',
  waiting_material: '待齐套',
  kitted: '已齐套',
  shortage: '缺料',

  cutting: '下料',
  pipe_cutting: '切管',
  welding: '焊接',
  polish: '打磨',
  grinding: '打磨',
  assemble: '总装',
  assembly: '总装',
  testing: '试水',
  packaging: '打包',
  sending: '发货',
  final_assembly: '总装完成',
  inspection: '交付检验',
  complete: '完成'
}

export const STATUS_TAG_TYPES = {
  draft: 'info',
  unconfirmed: 'info',
  pending_confirmation: 'warning',
  confirmed: 'success',
  closed: 'info',
  cancelled: 'danger',
  changed: 'warning',
  pending: 'warning',
  pending_confirm: 'warning',
  approved: 'success',
  rejected: 'danger',
  not_required: 'info',
  unmatched: 'info',
  not_planned: 'info',
  not_entered: 'info',
  inventory: 'success',
  production: 'warning',
  mixed: 'warning',
  service: 'info',
  no_delivery: 'success',
  partial: 'warning',
  non_physical_only: 'info',
  inventory_reserved_pending: 'warning',
  production_pending: 'warning',
  service_fulfilled: 'success',
  no_delivery_closed: 'success',
  reservation_pending: 'warning',
  reserved: 'success',
  fulfilled: 'success',
  open: 'warning',
  active: 'success',
  replaced: 'info',
  deleted: 'danger',
  matched: 'success',
  abnormal: 'danger',
  enabled: 'success',
  disabled: 'info',
  valid: 'success',
  invalid: 'danger',
  released: 'primary',
  waiting_release: 'warning',
  waiting_accept: 'warning',
  in_progress: 'success',
  paused: 'warning',
  completed: 'success',
  assembled: 'success',
  pending_destination: 'warning',
  pending_inspection: 'warning',
  inspecting: 'primary',
  inspection_passed: 'success',
  inspection_failed: 'danger',
  pending_receipt: 'warning',
  received: 'success',
  pending_issue: 'warning',
  partially_issued: 'warning',
  issued: 'success',
  pending_report: 'warning',
  partially_reported: 'warning',
  reported: 'success',
  ready: 'warning',
  accepted: 'primary',
  skipped: 'info',
  exception: 'danger',
  waiting_material: 'warning',
  kitted: 'success',
  shortage: 'danger'
}

export function statusText(value) {
  if (value === null || value === undefined || value === '') return '-'
  return STATUS_LABELS[value] || value
}

export function statusTag(value) {
  return STATUS_TAG_TYPES[value] || ''
}
