<template>
  <div class="form-list-page" v-loading="loading">
    <main>
      <header class="page-head"><div><h1>自定义表单管理</h1><p>先创建并发布表单，再在流程配置中选择“自定义表单”。</p></div><div><el-button size="small" @click="validateAll">表单完整性检查</el-button><el-button size="small" type="success" icon="el-icon-plus" @click="$router.push('/approvals/forms/create')">新建自定义表单</el-button></div></header>
      <section class="filters card"><label>业务模块<el-select v-model="filters.business_module" size="small" clearable placeholder="全部"><el-option v-for="item in modules" :key="item" :label="item" :value="item" /></el-select></label><label>状态<el-select v-model="filters.status" size="small" clearable placeholder="全部"><el-option label="已启用" value="enabled"/><el-option label="草稿" value="draft"/><el-option label="已停用" value="disabled"/></el-select></label><label class="keyword">表单编码/名称<el-input v-model.trim="filters.keyword" size="small" clearable placeholder="请输入表单编码或名称关键词" @keyup.enter.native="search"/></label><div class="filter-actions"><el-button size="small" type="success" @click="search">查询</el-button><el-button size="small" @click="reset">重置</el-button></div></section>
      <section class="stats"><article><i class="el-icon-files blue"/><div><span>表单总数</span><b>{{ summary.total||0 }}</b></div></article><article><i class="el-icon-circle-check green"/><div><span>已启用</span><b>{{ summary.enabled||0 }}</b></div></article><article><i class="el-icon-document orange"/><div><span>草稿</span><b>{{ summary.draft||0 }}</b></div></article><article><i class="el-icon-circle-close gray"/><div><span>已停用</span><b>{{ summary.disabled||0 }}</b></div></article></section>
      <section class="table-card card"><el-table :data="rows" size="mini" border><el-table-column prop="form_code" label="表单编码" min-width="155"/><el-table-column prop="form_name" label="表单名称" min-width="130"/><el-table-column prop="business_module" label="业务模块" width="105"/><el-table-column label="当前版本" width="82"><template slot-scope="{row}">v{{ row.current_version||'-' }}</template></el-table-column><el-table-column prop="field_count" label="字段数" width="70"/><el-table-column prop="linked_flow_count" label="已关联流程" width="92"/><el-table-column prop="submissions_count" label="申请记录" width="82"/><el-table-column label="状态" width="82"><template slot-scope="{row}"><el-tag size="mini" :type="statusTag(row.status)">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column label="更新时间" width="142"><template slot-scope="{row}">{{ time(row.updated_at) }}</template></el-table-column><el-table-column label="操作" width="246" fixed="right"><template slot-scope="{row}"><el-button type="text" size="mini" @click="edit(row)">编辑</el-button><el-button type="text" size="mini" @click="copy(row)">复制</el-button><el-button type="text" size="mini" @click="versions(row)">版本</el-button><el-button v-if="Number(row.current_version||0)>0" type="text" size="mini" @click="toggle(row)">{{ row.status==='enabled'?'停用':'启用' }}</el-button><el-button v-if="canDelete(row)" type="text" size="mini" class="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><footer><span>共 {{ total }} 条</span><el-pagination background layout="sizes, prev, pager, next, jumper" :current-page.sync="page" :page-size="perPage" :page-sizes="[10,20,50]" :total="total" @current-change="load" @size-change="sizeChange"/></footer></section>
    </main>
    <aside class="rules card"><h2><i class="el-icon-info blue"/> 自定义表单规则</h2><ul><li>表单发布后版本不可变</li><li>已被流程引用的表单禁止删除</li><li>修改后发布新版本</li><li>历史申请保留原表单快照</li></ul></aside>
  </div>
</template>

<script>
import { copyApprovalForm, deleteApprovalForm, getApprovalForm, getApprovalFormSummary, listApprovalForms, toggleApprovalForm, validateApprovalForm } from '@/api/erp/approval'
const blank=()=>({business_module:'',status:'',keyword:''})
export default{name:'ApprovalFormList',data:()=>({loading:false,rows:[],summary:{},filters:blank(),page:1,perPage:10,total:0,modules:['采购管理','销售管理','库存管理','财务管理','行政管理','其他']}),created(){this.loadAll()},methods:{async loadAll(){this.loading=true;try{await Promise.all([this.load(),this.loadSummary()])}finally{this.loading=false}},async load(){const{data}=await listApprovalForms({...this.filters,page:this.page,per_page:this.perPage});this.rows=data.data||[];this.total=Number(data.total||0)},async loadSummary(){const{data}=await getApprovalFormSummary();this.summary=data.data||{}},search(){this.page=1;this.load()},reset(){this.filters=blank();this.search()},sizeChange(v){this.perPage=v;this.page=1;this.load()},edit(row){this.$router.push(`/approvals/forms/${row.id}/edit`)},async copy(row){await this.$confirm(`复制表单“${row.form_name}”为新草稿？`,'复制表单');await copyApprovalForm(row.id);this.$message.success('已复制为新草稿');await this.loadAll()},async toggle(row){const enabled=row.status!=='enabled';await this.$confirm(`确认${enabled?'启用':'停用'}表单“${row.form_name}”？`,'状态确认',{type:'warning'});await toggleApprovalForm(row.id,enabled);this.$message.success(enabled?'表单已启用':'表单已停用');await this.loadAll()},async remove(row){await this.$confirm(`删除草稿“${row.form_name}”？删除后不可恢复。`,'删除确认',{type:'warning'});await deleteApprovalForm(row.id);this.$message.success('表单草稿已删除');await this.loadAll()},async versions(row){const{data}=await getApprovalForm(row.id);const versions=(data.data&&data.data.versions)||[];this.$alert(versions.map(v=>`v${v.version_no} · ${v.version_status==='published'?'已发布':'草稿'} · ${this.time(v.published_at||v.updated_at)} · ${v.published_by||v.updated_by||'-'}`).join('\n')||'暂无版本','版本记录',{customClass:'approval-version-dialog',confirmButtonText:'关闭'})},async validateAll(){let invalid=0;for(const row of this.rows){const{data}=await getApprovalForm(row.id);const schema=data.data&&data.data.editing_version&&data.data.editing_version.schema_snapshot||{};const result=await validateApprovalForm(schema);if(!result.data.data.valid)invalid++}this.$message[invalid?'warning':'success'](invalid?`当前页发现 ${invalid} 个表单不完整`:'当前页表单完整性检查通过')},canDelete(row){return row.status==='draft'&&Number(row.linked_flow_count||0)===0&&Number(row.submissions_count||0)===0},statusText(v){return({enabled:'已启用',draft:'草稿',disabled:'已停用'})[v]||v||'-'},statusTag(v){return({enabled:'success',draft:'warning',disabled:'info'})[v]||'info'},time(v){return v?String(v).replace('T',' ').replace(/\.\d+Z$/,'').slice(0,16):'-'}}}
</script>

<style scoped>
.form-list-page{min-height:calc(100vh - 52px);padding:18px;display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:18px;background:#f7f8fa;color:#172535}.form-list-page main{min-width:0}.page-head{height:72px;display:flex;align-items:flex-start;justify-content:space-between}.page-head h1{margin:2px 0 7px;font-size:22px}.page-head p{margin:0;color:#5f7083;font-size:12px}.card{background:#fff;border:1px solid #e3e8ed;border-radius:6px}.filters{display:grid;grid-template-columns:220px 220px minmax(300px,1fr) auto;gap:16px;align-items:end;padding:18px;margin-bottom:18px}.filters label{display:flex;flex-direction:column;gap:8px;font-size:12px}.filter-actions{display:flex;gap:8px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-bottom:18px}.stats article{height:108px;padding:0 28px;display:flex;align-items:center;gap:28px;background:#fff;border:1px solid #e3e8ed;border-radius:6px}.stats i{font-size:42px}.stats span{display:block;color:#45586d;font-size:14px}.stats b{display:block;margin-top:8px;font-size:28px}.table-card{overflow:hidden}.table-card ::v-deep .el-table th{height:46px;background:#f7f9fb;color:#24364a}.table-card ::v-deep .el-table td{height:52px}.table-card footer{height:64px;padding:0 16px;display:flex;align-items:center;justify-content:space-between;font-size:12px}.rules{align-self:start;margin-top:90px;padding:22px}.rules h2{margin:0 0 24px;font-size:18px}.rules ul{padding-left:19px;margin:0}.rules li{margin-bottom:23px;line-height:1.6;font-size:13px}.blue{color:#247fea}.green{color:#0aa05a}.orange{color:#f18a0b}.gray{color:#8793a1}.danger{color:#e55353!important}@media(max-width:1450px){.form-list-page{grid-template-columns:minmax(0,1fr) 250px;gap:12px;padding:14px}.filters{grid-template-columns:180px 180px minmax(260px,1fr) auto;gap:10px}.stats{gap:10px}.stats article{padding:0 18px;gap:18px}.rules{padding:16px}}@media(max-width:1150px){.form-list-page{grid-template-columns:1fr}.rules{margin-top:0}.filters{grid-template-columns:repeat(2,minmax(180px,1fr))}.filter-actions{align-self:end}.stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.page-head{height:auto;flex-direction:column;gap:12px;margin-bottom:12px}.filters,.stats{grid-template-columns:1fr}.table-card{overflow-x:auto}.table-card .el-table{min-width:1200px}}
</style>
